---
title: "Python Introduction (exercise solutions)"
jupyter: python3
format: html
execute:
  warning: false
  message: false
---

## Exercise 0 solution

1. Open the `Characters.txt` file and read its contents.

```{python}
characters_file = open("Characters.txt")
characters_txt = characters_file.read()
```

2. Split text on newlines to produce a list with one element per line. Store the result as `alice_characters`. HINT: you can split on newlines using the `splitlines()` method.

```{python}
alice_characters = characters_txt.splitlines()
alice_characters
```

## Exercise 1 solution

1. Count the number of main characters in the story (i.e., get the length of the list you created in previous exercise).

```{python}
len(alice_characters)
```

2. Extract and print just the first character from the list you created in the previous exercise.

```{python}
print(alice_characters[0])
```

3. Test whether the length of the 3rd and 8th character's names are equal. Test whether the length of the 3rd character's name is greater than or equal to the length of the 6th character's name. Now test whether EITHER of the above conditions are true. HINT: use the `len()` function.

```{python}
len(alice_characters[2]) == len(alice_characters[7]) or len(alice_characters[2]) >= len(alice_characters[5])
```

4. (BONUS, optional): Sort the list you created in step 2 alphabetically, and then extract the last element.

```{python}
alice_characters.sort()
alice_characters[-1]
```

## Exercise 2 solution

1. Make sure you have both the text and the list of characters. Open and read both `Alice_in_wonderland.txt` and `Characters.txt` if you have not already done so.

```{python}
characters_txt = open("Characters.txt").read()
alice_txt = open("Alice_in_wonderland.txt").read()
```

2. Which chapter has the most words? Split the text into chapters (i.e., split on "CHAPTER ") and use a for-loop to iterate over the chapters. For each chapter, split it into words and calculate the length.

```{python}
words_per_chapter = []

for chapter in alice_chapters:
    words_per_chapter.append(len(chapter.split()))

print(words_per_chapter)
```

3. How many times is each character mentioned in the text? Iterate over the list of characters using a for-loop. For each character, call the count method with that character as the argument.

```{python}
num_per_character = []

for character in characters_txt.splitlines():
    num_per_character.append(alice_txt.count(character))

print(num_per_character)
```

4. (BONUS, optional): Put the character counts computed above in a dictionary with character names as the keys and counts as the values.

```{python}
characters = characters_txt.splitlines()
dict(zip(characters, num_per_character))
```

