language: r
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

r_packages:
  - bookdown

pandoc_version: 1.19.2.1

sudo: false

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh

notifications:
  email: false

#before_deploy:
  # Set up git user name and tag this commit
#  - git config --local user.name "stevenworthington"
#  - git config --local user.email "sworthington@iq.harvard.edu"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG

deploy:
    provider: pages               # Specify the gh-pages deployment method
    skip_cleanup: true            # Don't remove files
    local_dir: docs               # Deploy the docs folder
    github_token: $GITHUB_PAT     # Set in travis-ci.org dashboard
    on:                           # set build to deploy only when conditions are met
      branch: master
    target_branch: gh-pages

#deploy:
#    provider: releases
#    skip_cleanup: true
#    api_key: $GITHUB_PAT
#    file:
#      - "dss-rbuild.pdf"
#      - "dss-rbuild.tex"
#    on:
#      branch: gh-pages
#      tags: false
#    overwrite: true
