---
title: "Data Science Workshops"
author: ""
date: "`r format(Sys.Date(), '%B %Y')`"
description: "Data Science Workshops"
github-repo: "IQSS/dss-workshops"
site: "bookdown::bookdown_site"
documentclass: book
geometry: "margin=1.5in"
biblio-style: apalike
link-citations: yes
---


Materials for the software workshops held at the [Institute for Quantitative Social Science](http://dss.iq.harvard.edu/) and [Harvard Business School](https://training.rcs.hbs.org) at Harvard University.


# Table of Contents {-}

* [Data Science Tools](./DataScienceTools.html)
* [R Installation](./Rinstall.html)
* [R Introduction](./Rintro.html)
* [R Regression Models](./Rmodels.html)
* [R Graphics](./Rgraphics.html)
* [R Data Wrangling](./RDataWrangling.html)
* [Python Installation](./PythonInstall.html)
* [Python Introduction](./PythonIntro.html)
* [Python Web-Scraping](./PythonWebScrape.html)
* [Stata Installation](./StataInstall.html)
* [Stata Introduction](./StataIntro.html)
* [Stata Data Management](./StataDataManage.html)
* [Stata Regression Models](./StataModels.html)
* [Stata Graphics](./StataGraphics.html)


## Contributors {-}

The contents of these workshops are the result of a collaborative effort from members of the [Data Science Services](http://dss.iq.harvard.edu) team at IQSS and the [Research Computing Services](https://training.rcs.hbs.org) team at HBS. The main contributors are: Ista Zahn, Steve Worthington, Bob Freeman, Jinjie Liu, Yihan Wang, and Victoria Liublinska.

These workshops are a work-in-progress, please provide feedback! Email: help@iq.harvard.edu
