---
title: "Resources"
---

The links that used to close every workshop, gathered here once. All of the software is free.

## IQSS

- Training materials: <https://iqss.github.io/dss-training/>
- Data Science Services: <https://www.iq.harvard.edu/data-science-services>
- Cluster computing, the IQSS quick-start for FASRC's Cannon: <https://docs.rc.fas.harvard.edu/kb/iqss-cannon-quickstart-guide/>

## R

### Software

- R and R packages: <http://cran.r-project.org>
- Positron: <https://positron.posit.co/download>
- RStudio: <https://posit.co/download/rstudio-desktop/>
- ESS (Emacs R package): <http://ess.r-project.org/>

### Cheatsheets

- Posit cheatsheets, ggplot2 and the tidyverse among them: <https://posit.co/resources/cheatsheets/>

### Tutorials and books

- swirl, R lessons inside R: <https://swirlstats.com/>
- R for Data Science: <https://r4ds.had.co.nz/>
- Advanced R: <http://adv-r.had.co.nz/>
- R Markdown lessons: <https://rmarkdown.rstudio.com/lesson-1.html>
- Pluralsight: <https://www.pluralsight.com/search?q=R>
- DataCamp: <https://www.datacamp.com/>
- R for Programmers (Norman Matloff, UC Davis): <https://web.cs.ucdavis.edu/~matloff/>
- Calling C and Fortran from R (Charles Geyer, University of Minnesota): <http://www.stat.umn.edu/~charlie/rc/>
- State of the Art in Parallel Computing with R (Schmidberger et al.): <https://www.jstatsoft.org/v31/i01>

### Documentation and help

- R manuals: <http://cran.r-project.org/manuals.html>
- Documentation and tutorials: <http://cran.r-project.org/other-docs.html>
- Recommended packages by topic (CRAN task views): <http://cran.r-project.org/web/views/>
- R-help mailing list: <https://stat.ethz.ch/mailman/listinfo/r-help>
- StackOverflow: <http://stackoverflow.com/questions/tagged/r>
- R-Bloggers: <https://www.r-bloggers.com/>

### Coming from another language

- Stata: <http://www.princeton.edu/~otorres/RStata.pdf>
- SAS or SPSS: <http://r4stats.com/books/free-version/>
- Matlab: <http://www.math.umaine.edu/~hiebeler/comp/matlabR.pdf>
- Python: <http://mathesaurus.sourceforge.net/matlab-python-xref.pdf>

### ggplot2

- Reference: <https://ggplot2.tidyverse.org/reference/>
- Examples: <http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html>
- Tutorial: <https://uc-r.github.io/ggplot_intro>
- Mailing list: <http://groups.google.com/group/ggplot2>
- Wiki: <https://github.com/hadley/ggplot2/wiki>
- Website: <http://had.co.nz/ggplot2/>
- StackOverflow: <http://stackoverflow.com/questions/tagged/ggplot>

## Python

### Graphics

- matplotlib: <https://matplotlib.org/>
- seaborn: <https://seaborn.pydata.org/>
- plotly: <https://plot.ly/python/>

### Quantitative data analysis

- numpy: <http://www.numpy.org/>
- scipy: <https://www.scipy.org/>
- pandas: <https://pandas.pydata.org/>
- scikit-learn: <http://scikit-learn.org/stable/>
- statsmodels: <http://www.statsmodels.org/stable/>

### Text analysis

- textblob: <https://textblob.readthedocs.io/en/dev/>
- nltk: <http://www.nltk.org/>
- Gensim: <https://radimrehurek.com/gensim/>

### Web scraping

- scrapy: <https://scrapy.org/>
- requests: <http://docs.python-requests.org/en/master/>
- lxml: <https://lxml.de/>
- BeautifulSoup: <https://www.crummy.com/software/BeautifulSoup/>

### Social network analysis

- networkx: <https://networkx.github.io/>
- graph-tool: <https://graph-tool.skewed.de/>

## Stata

- UCLA statistical consulting, Stata pages: <https://stats.oarc.ucla.edu/stata/>
- Stata documentation: <http://www.stata.com/help.cgi?contents>
- Statalist: <http://www.stata.com/statalist/>
