{
  "hash": "17c67dc8ee93999368bcdc7cb177d362",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R Regression Models\"\naliases:\n  - /Rmodels.html\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n**Topics**\n\n* Formula interface for model specification\n* Function methods for extracting quantities of interest from models\n* Contrasts to test specific hypotheses\n* Model comparisons\n* Predicted marginal effects\n* Modeling continuous and binary outcomes\n* Modeling clustered data\n\n## Setup\n\n### Software and Materials\n\nFollow the [R Installation](install.qmd) instructions and ensure that you can successfully start RStudio.\n\n### Class Structure\n\nInformal - Ask questions at any time. Really!\n\nCollaboration is encouraged - please spend a minute introducing yourself to your neighbors!\n\n### Prerequisites\n\nThis is an intermediate R course:\n\n* Assumes working knowledge of R\n* Relatively fast-paced\n* This is not a statistics course! We will teach you *how* to fit models in R, but we assume you know the theory behind the models.\n\n### Goals\n\n::: {.callout-tip}\n\nWe will learn about the R modeling ecosystem by fitting a variety of statistical models to different datasets. In particular, our goals are to learn about:\n\n1. Modeling workflow\n2. Visualizing and summarizing data before modeling\n3. Modeling continuous outcomes\n4. Modeling binary outcomes\n5. Modeling clustered data\n\nWe will not spend much time *interpreting* the models we fit, since this is not a statistics workshop. But, we will walk you through how model results are organized and orientate you to where you can find typical quantities of interest.\n\n:::\n\n### Launch an R session\n\nStart RStudio and create a new project:\n\n1. On Mac, RStudio will be in your applications folder. On Windows, click the start button and search for RStudio. \n2. In RStudio go to `File -> New Project`. Choose `Existing Directory` and browse to the workshop materials directory on your desktop. This will create an `.Rproj` file for your project and will automaticly change your working directory to the workshop materials directory. \n3. Choose `File -> Open File` and select the file with the word \"BLANK\" in the name.\n\n### Packages\n\nYou should have already installed the `tidyverse` and `rmarkdown` packages onto your computer before the workshop --- see [R Installation](install.qmd). Now let's load these packages into the search path of our R session.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(rmarkdown)\n```\n:::\n\n\nFinally, lets install some packages that will help with modeling:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"lme4\")\nlibrary(lme4)  # for mixed models\n\n# install.packages(\"emmeans\")\nlibrary(emmeans)  # for marginal effects\n\n# install.packages(\"effects\")\nlibrary(effects)  # for predicted marginal means\n```\n:::\n\n\n## Modeling workflow\n\nBefore we delve into the details of how to fit models in R, it's worth taking a step back and thinking more broadly about the components of the modeling process. These can roughly be divided into 3 stages:\n\n1. Pre-estimation\n2. Estimation\n3. Post-estimaton\n\nAt each stage, the goal is to complete a different task (e.g., to clean data, fit a model, test a hypothesis), but the process is sequential --- we move through the stages in order (though often many times in one project!)\n\n![](images/models/R_model_pipeline.png)\n\nThroughout this workshop we will go through these stages several times as we fit different types of model.\n\n## R modeling ecosystem\n\nThere are literally hundreds of R packages that provide model fitting functionality. We're going to focus on just two during this workshop --- `stats`, from Base R, and `lme4`. It's a good idea to look at [CRAN Task Views](https://cran.r-project.org/web/views/) when trying to find a modeling package for your needs, as they provide an extensive curated list. But, here's a more digestable table showing some of the most popular packages for particular types of model.\n\n| Models              | Packages                               |             \n|:--------------------|:---------------------------------------|\n| Generalized linear  | `stats`, `biglm`, `MASS`, `robustbase` | \n| Mixed effects       | `lme4`, `nlme`, `glmmTMB`, `MASS`      |                                     \n| Econometric         | `pglm`, `VGAM`, `pscl`, `survival`     | \n| Bayesian            | `brms`, `blme`, `MCMCglmm`, `rstan`    | \n| Machine learning    | `mlr`, `caret`, `h2o`, `tensorflow`    | \n\n## Before fitting a model\n\n::: {.callout-note}\n\n**GOAL: To learn about the data by creating summaries and visualizations.**\n\n:::\n\nOne important part of the pre-estimation stage of model fitting, is gaining an understanding of the data we wish to model by creating plots and summaries. Let's do this now.\n\n### Load the data\n\nList the data files we're going to work with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist.files(\"dataSets\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Exam.rds\"          \"NatHealth2008MI\"   \"NatHealth2011.rds\"\n[4] \"states.rds\"       \n```\n\n\n:::\n:::\n\n\nWe're going to use the `states` data first, which originally appeared in *Statistics with Stata* by Lawrence C. Hamilton.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # read the states data\n  states <- read_rds(\"dataSets/states.rds\")\n\n  # look at the last few rows\n  tail(states)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           state  region     pop  area density metro waste energy miles toxic\n46       Vermont N. East  563000  9249   60.87  23.4  0.69    232  10.4  1.81\n47      Virginia   South 6187000 39598  156.25  72.5  1.45    306   9.7 12.87\n48    Washington    West 4867000 66582   73.10  81.7  1.05    389   9.2  8.51\n49 West Virginia   South 1793000 24087   74.44  36.4  0.95    415   8.6 21.30\n   green house senate csat vsat msat percent expense income high college\n46 15.17    85     94  890  424  466      68    6738 34.717 80.8    24.3\n47 18.72    33     54  890  424  466      60    4836 38.838 75.2    24.5\n48 16.51    52     64  913  433  480      49    5000 36.338 83.8    22.9\n49 51.14    48     57  926  441  485      17    4911 24.233 66.0    12.3\n [ reached 'max' / getOption(\"max.print\") -- omitted 2 rows ]\n```\n\n\n:::\n:::\n\n\nHere's a table that describes what each variable in the dataset represents:\n\n| Variable | Description                                        |\n|:---------|:---------------------------------------------------|\n| csat     | Mean composite SAT score                           |\n| expense  | Per pupil expenditures                             |\n| percent  | % HS graduates taking SAT                          |\n| income   | Median household income, $1,000                    |\n| region   | Geographic region: West, N. East, South, Midwest   |\n| house    | House '91 environ. voting, %                       |\n| senate   | Senate '91 environ. voting, %                      |\n| energy   | Per capita energy consumed, Btu                    |\n| metro    | Metropolitan area population, %                    |\n| waste    | Per capita solid waste, tons                       |\n\n### Examine the data\n\nStart by examining the data to check for problems.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # summary of expense and csat columns, all rows\n  states_ex_sat <- states %>% \n      select(expense, csat)\n  \n  summary(states_ex_sat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    expense          csat       \n Min.   :2960   Min.   : 832.0  \n 1st Qu.:4352   1st Qu.: 888.0  \n Median :5000   Median : 926.0  \n Mean   :5236   Mean   : 944.1  \n 3rd Qu.:5794   3rd Qu.: 997.0  \n Max.   :9259   Max.   :1093.0  \n```\n\n\n:::\n\n```{.r .cell-code}\n  # correlation between expense and csat\n  cor(states_ex_sat, use = \"pairwise\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           expense       csat\nexpense  1.0000000 -0.4662978\ncsat    -0.4662978  1.0000000\n```\n\n\n:::\n:::\n\n\n### Plot the data\n\nPlot the data to look for multivariate outliers, non-linear relationships etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # scatter plot of expense vs csat\n  qplot(x = expense, y = csat, geom = \"point\", data = states_ex_sat)\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nObviously, in a real project, you would want to spend more time investigating the data,\nbut we'll now move on to modeling.\n\n## Models with continuous outcomes\n\n::: {.callout-note}\n\n**GOAL: To learn about the R modeling ecosystem by fitting ordinary least squares (OLS) models.** In particular:\n\n1. Formula representation of model specification\n2. Model classes\n3. Function methods\n4. Model comparison\n\n:::\n\nOnce the data have been inspected and cleaned, we can start estimating models. The simplest models (but those with the most assumptions) are those for continuous and unbounded outcomes. Typically, for these outcomes, we'd use a model estimated using Ordinary Least Lquares (OLS), which in R can be fit with the `lm()` (linear model) function.\n\nTo fit a model in R, we first have to convert our theoretical model into a `formula` --- a symbolic representation of the model in R syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# formula for model specification\noutcome ~ pred1 + pred2 + pred3\n\n# NOTE the ~ is a tilde\n```\n:::\n\n\nFor example, the following theoretical model predicts SAT scores based on per-pupil expenditures:\n\n::: {.callout-note}\n\n$$\nSATscores_i = \\beta_{0}1 + \\beta_1expenditures_i + \\epsilon_i\n$$\n\n:::\n\nWe can use `lm()` to fit this model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # fit our regression model\n  sat_mod <- lm(csat ~ 1 + expense, # regression formula\n                data = states) # data \n\n  # look at the basic printed output\n  sat_mod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = csat ~ 1 + expense, data = states)\n\nCoefficients:\n(Intercept)      expense  \n 1060.73244     -0.02228  \n```\n\n\n:::\n:::\n\n\nThe default printed output from the fitted model is very austere --- just point estimates of the coefficients. We can get more information by passing the fitted model object to the `summary()` function, which provides standard errors, test statistics, and p-values for individual coefficients, as well as goodness-of-fit measures for the overall model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # get more informative summary information \n  summary(sat_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = csat ~ 1 + expense, data = states)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-131.811  -38.085    5.607   37.852  136.495 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.061e+03  3.270e+01   32.44  < 2e-16 ***\nexpense     -2.228e-02  6.037e-03   -3.69 0.000563 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.81 on 49 degrees of freedom\nMultiple R-squared:  0.2174,\tAdjusted R-squared:  0.2015 \nF-statistic: 13.61 on 1 and 49 DF,  p-value: 0.0005631\n```\n\n\n:::\n:::\n\n\nIf we just want to inspect the coefficients, we can further pipe the summary output into the function `coef()` to obtain just the table of coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # show only the regression coefficients table \n  summary(sat_mod) %>% coef() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept) 1060.73244395 32.700896736 32.437412 8.878411e-35\nexpense       -0.02227565  0.006037115 -3.689783 5.630902e-04\n```\n\n\n:::\n:::\n\n\n### Why is the association between expense & SAT scores *negative*?\n\nMany people find it surprising that the per-capita expenditure on students is negatively related to SAT scores. The beauty of multiple regression is that we can try to pull these apart. What would the association between expense and SAT scores be if there were no difference among the states in the percentage of students taking the SAT?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  lm(csat ~ 1 + expense + percent, data = states) %>% \n  summary() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = csat ~ 1 + expense + percent, data = states)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-62.921 -24.318   1.741  15.502  75.623 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 989.807403  18.395770  53.806  < 2e-16 ***\nexpense       0.008604   0.004204   2.046   0.0462 *  \npercent      -2.537700   0.224912 -11.283 4.21e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 31.62 on 48 degrees of freedom\nMultiple R-squared:  0.7857,\tAdjusted R-squared:  0.7768 \nF-statistic: 88.01 on 2 and 48 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### The `lm` class & methods\n\nOkay, we fitted our model. Now what? Typically, the main goal in the **post-estimation stage** of analysis\nis to extract **quantities of interest** from our fitted model. These quantities could be things like:\n\n1. Testing whether one group is different on average from another group\n2. Generating average response values from the model for interesting combinations of predictor values\n3. Calculating interval estimates for particular coefficients\n\nBut before we can do any of that, we need to know more about **what a fitted model actually is,**\n**what information it contains, and how we can extract from it information that we want to report**.\n\nTo understand what a fitted model object is and what information we can extract from it, we need to know about the concepts of **class** and **method**. A class defines a type of object, describing what properties it possesses, how it behaves, and how it relates to other types of objects. Every object must be an instance of some class. A method is a function associated with a particular type of object.\n\nLet's start by examining the class of the model object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # what class of object is the fitted model?\n  class(sat_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"lm\"\n```\n\n\n:::\n:::\n\n\nWe can see that the fitted model object is of class `lm`, which stands for linear model. What quantities are stored within this model object? \n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # what are the elements stored within the fitted model object?\n  names(sat_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"coefficients\"  \"residuals\"     \"effects\"       \"rank\"         \n [5] \"fitted.values\" \"assign\"        \"qr\"            \"df.residual\"  \n [9] \"xlevels\"       \"call\"          \"terms\"         \"model\"        \n```\n\n\n:::\n:::\n\n\nWe can see that 12 different things are stored within a fitted model of class `lm`. In what structure are these quantities organized?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # what is the structure of the fitted model object?\n  str(sat_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 12\n $ coefficients : Named num [1:2] 1060.7324 -0.0223\n  ..- attr(*, \"names\")= chr [1:2] \"(Intercept)\" \"expense\"\n $ residuals    : Named num [1:51] 11.1 44.8 -32.7 26.7 -63.7 ...\n  ..- attr(*, \"names\")= chr [1:51] \"1\" \"2\" \"3\" \"4\" ...\n $ effects      : Named num [1:51] -6742.2 220.7 -31.7 29.7 -63.2 ...\n  ..- attr(*, \"names\")= chr [1:51] \"(Intercept)\" \"expense\" \"\" \"\" ...\n $ rank         : int 2\n $ fitted.values: Named num [1:51] 980 875 965 978 961 ...\n  ..- attr(*, \"names\")= chr [1:51] \"1\" \"2\" \"3\" \"4\" ...\n $ assign       : int [1:2] 0 1\n $ qr           :List of 5\n  ..$ qr   : num [1:51, 1:2] -7.14 0.14 0.14 0.14 0.14 ...\n  .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. ..$ : chr [1:51] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. ..$ : chr [1:2] \"(Intercept)\" \"expense\"\n  .. ..- attr(*, \"assign\")= int [1:2] 0 1\n  ..$ qraux: num [1:2] 1.14 1.33\n  ..$ pivot: int [1:2] 1 2\n  ..$ tol  : num 1e-07\n  ..$ rank : int 2\n  ..- attr(*, \"class\")= chr \"qr\"\n $ df.residual  : int 49\n $ xlevels      : Named list()\n $ call         : language lm(formula = csat ~ 1 + expense, data = states)\n $ terms        :Classes 'terms', 'formula'  language csat ~ 1 + expense\n  .. ..- attr(*, \"variables\")= language list(csat, expense)\n  .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. ..$ : chr [1:2] \"csat\" \"expense\"\n  .. .. .. ..$ : chr \"expense\"\n  .. ..- attr(*, \"term.labels\")= chr \"expense\"\n  .. ..- attr(*, \"order\")= int 1\n  .. ..- attr(*, \"intercept\")= int 1\n  .. ..- attr(*, \"response\")= int 1\n  .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. ..- attr(*, \"predvars\")= language list(csat, expense)\n  .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. ..- attr(*, \"names\")= chr [1:2] \"csat\" \"expense\"\n $ model        :'data.frame':\t51 obs. of  2 variables:\n  ..$ csat   : int [1:51] 991 920 932 1005 897 959 897 892 840 882 ...\n  ..$ expense: int [1:51] 3627 8330 4309 3700 4491 5064 7602 5865 9259 5276 ...\n  ..- attr(*, \"terms\")=Classes 'terms', 'formula'  language csat ~ 1 + expense\n  .. .. ..- attr(*, \"variables\")= language list(csat, expense)\n  .. .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. .. ..$ : chr [1:2] \"csat\" \"expense\"\n  .. .. .. .. ..$ : chr \"expense\"\n  .. .. ..- attr(*, \"term.labels\")= chr \"expense\"\n  .. .. ..- attr(*, \"order\")= int 1\n  .. .. ..- attr(*, \"intercept\")= int 1\n  .. .. ..- attr(*, \"response\")= int 1\n  .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. .. ..- attr(*, \"predvars\")= language list(csat, expense)\n  .. .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. .. ..- attr(*, \"names\")= chr [1:2] \"csat\" \"expense\"\n - attr(*, \"class\")= chr \"lm\"\n```\n\n\n:::\n:::\n\n\nWe can see that the fitted model object is a `list` structure (a container that can hold different types of objects). What have we learned by examining the fitted model object? We can see that the default output we get when printing a fitted model of class `lm` is only a small subset of the information stored within the model object. How can we access other quantities of interest from the model?\n\nWe can use **methods** (functions designed to work with specific classes of object) to extract various quantities from a fitted model object (sometimes these are referred to as **extractor functions**). A list of all the available methods for a given class of object can be shown by using the `methods()` function with the `class` argument set to the class of the model object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # methods for class `lm`\n  methods(class = class(sat_mod))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] add1           alias          anova          case.names     coerce        \n [6] confint        cooks.distance deviance       dfbeta         dfbetas       \n[11] dffits         drop1          dummy.coef     Effect         effects       \n[16] emm_basis      extractAIC     family         formula        fortify       \n[21] hatvalues      influence      initialize     kappa          labels        \n[26] logLik         model.frame    model.matrix   nobs           plot          \n[31] predict        print          proj           qqnorm         qr            \n[36] recover_data   residuals      rstandard      rstudent       show          \n[41] simulate       slotsFromS3    summary        variable.names vcov          \nsee '?methods' for accessing help and source code\n```\n\n\n:::\n:::\n\n\nThere are 44 methods available for the `lm` class. We've already seen the `summary()` method for `lm`, which is always a good place to start after fitting a model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # summary table\n  summary(sat_mod) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = csat ~ 1 + expense, data = states)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-131.811  -38.085    5.607   37.852  136.495 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.061e+03  3.270e+01   32.44  < 2e-16 ***\nexpense     -2.228e-02  6.037e-03   -3.69 0.000563 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.81 on 49 degrees of freedom\nMultiple R-squared:  0.2174,\tAdjusted R-squared:  0.2015 \nF-statistic: 13.61 on 1 and 49 DF,  p-value: 0.0005631\n```\n\n\n:::\n:::\n\n\nWe can use the `confint()` method to get interval estimates for our coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # confidence intervals\n  confint(sat_mod) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %        97.5 %\n(Intercept) 995.01753164 1126.44735626\nexpense      -0.03440768   -0.01014361\n```\n\n\n:::\n:::\n\n\nAnd we can use the `anova()` method to get an ANOVA-style table of the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # ANOVA table\n  anova(sat_mod)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: csat\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nexpense    1  48708   48708  13.614 0.0005631 ***\nResiduals 49 175306    3578                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nHow does R know which method to call for a given object? R uses **generic functions**, which provide access to the methods. **Method dispatch** takes place based on the class of the first argument to the generic function. For example, for the generic function `summary()` and an object of class `lm`, the method dispatched will be `summary.lm()`. Here's a schematic that shows the process of method dispatch in action:\n\n![](images/models/methods.png)\n\nFunction methods always take the form `generic.method()`. Let's look at all the methods for the generic `summary()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # methods for generic `summary()` function\n  methods(\"summary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] summary,ANY-method                  summary,DBIObject-method           \n  [3] summary,diagonalMatrix-method       summary,sparseMatrix-method        \n  [5] summary.aareg*                      summary.allFit*                    \n  [7] summary.aov                         summary.aovlist*                   \n  [9] summary.aspell*                     summary.cch*                       \n [11] summary.check_packages_in_dir*      summary.connection                 \n [13] summary.corAR1*                     summary.corARMA*                   \n [15] summary.corCAR1*                    summary.corCompSymm*               \n [17] summary.corExp*                     summary.corGaus*                   \n [19] summary.corIdent*                   summary.corLin*                    \n [21] summary.corNatural*                 summary.corRatio*                  \n [23] summary.corSpher*                   summary.corStruct*                 \n [25] summary.corSymm*                    summary.coxph*                     \n [27] summary.coxph.penal*                summary.data.frame                 \n [29] summary.Date                        summary.DBIrepdesign*              \n [31] summary.DBIsvydesign*               summary.default                    \n [33] summary.difftime                    summary.Duration*                  \n [35] summary.ecdf*                       summary.eff*                       \n [37] summary.efflatent*                  summary.efflist*                   \n [39] summary.effpoly*                    summary.emm_list*                  \n [41] summary.emmGrid*                    summary.factor                     \n [43] summary.free1way*                   summary.get_predicted*             \n [45] summary.ggplot2::ggplot*            summary.glht_list*                 \n [47] summary.glm                         summary.gls*                       \n [49] summary.hcl_palettes*               summary.infl*                      \n [51] summary.Interval*                   summary.lm                         \n [53] summary.lme*                        summary.lmList*                    \n [55] summary.lmList4*                    summary.loess*                     \n [57] summary.loglm*                      summary.manova                     \n [59] summary.matrix                      summary.merMod*                    \n [61] summary.MIresult*                   summary.mlm*                       \n [63] summary.mlm.efflist*                summary.modelStruct*               \n [65] summary.multiframe*                 summary.multinom*                  \n [67] summary.negbin*                     summary.nls*                       \n [69] summary.nlsList*                    summary.nnet*                      \n [71] summary.packageStatus*              summary.pdBlocked*                 \n [73] summary.pdCompSymm*                 summary.pdDiag*                    \n [75] summary.pdIdent*                    summary.pdLogChol*                 \n [77] summary.pdMat*                      summary.pdNatural*                 \n [79] summary.pdSymm*                     summary.Period*                    \n [81] summary.polr*                       summary.POSIXct                    \n [83] summary.POSIXlt                     summary.ppr*                       \n [85] summary.pps*                        summary.prcomp*                    \n [87] summary.prcomplist*                 summary.predictorefflist*          \n [89] summary.princomp*                   summary.proc_time                  \n [91] summary.pyears*                     summary.ratetable*                 \n [93] summary.reStruct*                   summary.rlang_error*               \n [95] summary.rlang_message*              summary.rlang_trace*               \n [97] summary.rlang_warning*              summary.rlang:::list_of_conditions*\n [99] summary.rlm*                        summary.shingle*                   \n [ reached 'max' / getOption(\"max.print\") -- omitted 42 entries ]\nsee '?methods' for accessing help and source code\n```\n\n\n:::\n:::\n\n\nThere are 137 `summary()` methods and counting! \n\nIt's always worth examining whether the class of model you've fitted has a method for a particular generic extractor function. Here's a summary table of some of the most often used extractor functions, which have methods for a wide range of model classes. These are post-estimation tools you will want in your toolbox:\n\n| Function      | Package   | Output                                                  |\n|:--------------|:----------|:--------------------------------------------------------|\n| `summary()`   | `stats`   | standard errors, test statistics, p-values, GOF stats   |\n| `confint()`   | `stats`   | confidence intervals                                    |\n| `anova()`     | `stats`   | anova table (one model), model comparison (> one model) |\n| `coef()`      | `stats`   | point estimates                                         |\n| `drop1()`     | `stats`   | model comparison                                        |\n| `predict()`   | `stats`   | predicted response values (for observed or new data)    |\n| `fitted()`    | `stats`   | predicted response values (for observed data only)      |\n| `residuals()` | `stats`   | residuals                                               |\n| `rstandard()` | `stats`   | standardized residuals                                  |\n| `fixef()`     | `lme4`    | fixed effect point estimates (mixed models only)        |\n| `ranef()`     | `lme4`    | random effect point estimates (mixed models only)       |\n| `coef()`      | `lme4`    | empirical Bayes estimates (mixed models only)           |\n| `allEffects()`| `effects` | predicted marginal means                                |\n| `emmeans()`   | `emmeans` | predicted marginal means & marginal effects             |\n| `margins()`   | `margins` | predicted marginal means & marginal effects             |\n\n### OLS regression assumptions\n\nOLS regression relies on several assumptions, including:\n\n1. The model includes all relevant variables (i.e., no omitted variable bias).\n2. The model is linear in the parameters (i.e., the coefficients and error term).\n3. The error term has an expected value of zero.\n4. All right-hand-side variables are uncorrelated with the error term.\n5. No right-hand-side variables are a perfect linear function of other RHS variables.\n6. Observations of the error term are uncorrelated with each other.\n7. The error term has constant variance (i.e., homoscedasticity).\n8. (Optional - only needed for inference). The error term is normally distributed.\n\nInvestigate assumptions #7 and #8 visually by plotting your model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # split plotting area into 2 x 2 grid\n  par(mfrow = c(2, 2))\n\n  # plot model diagnostics\n  plot(sat_mod)\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n### Comparing models\n\nDo congressional voting patterns predict SAT scores over and above expense? To find out, let's fit two models and compare them. First, let's create a new cleaned dataset that omits missing values in the variables we will use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# drop missing values for the 4 variables of interest\nstates_voting_cleaned <- states %>%\n    select(csat, expense, house, senate) %>%\n    drop_na()\n```\n:::\n\n\nThe `drop_na()` function omits rows with missing values --- that is, it performs *listwise deletion* of observations. In some situations, we may need more flexibility. If, for example, we only want to exclude rows that have missing data for a subset of variables, we could do the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # pseudocode\n  df <- df %>%\n    filter(!na.omit(var_name))\n```\n:::\n\n\nNow that we have a dataset with complete cases, let's fit a more elaborate model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # fit another model, adding house and senate as predictors\n  sat_voting_mod <- lm(csat ~ 1 + expense + house + senate,\n                       data = states_voting_cleaned)\n\n  summary(sat_voting_mod) %>% coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept) 1086.08037734 35.677308643 30.441769 3.964376e-32\nexpense       -0.01997159  0.007781131 -2.566670 1.358758e-02\nhouse         -1.42370479  0.519352260 -2.741309 8.686069e-03\nsenate         0.53984781  0.473469183  1.140196 2.601066e-01\n```\n\n\n:::\n:::\n\n\nTo compare models, *we must fit them to the same data*. This is why we needed to clean the dataset. Now let's update our first model to use these cleaned data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # update model using the cleaned data\n  sat_mod <- sat_mod %>%\n      update(data = states_voting_cleaned)\n\n  # compare using an F-test with the anova() function\n  anova(sat_mod, sat_voting_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: csat ~ 1 + expense\nModel 2: csat ~ 1 + expense + house + senate\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1     48 175049                              \n2     46 149497  2     25552 3.9312 0.02654 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Exercise 0\n\n**Ordinary least squares regression**\n\nUse the `states` data set. Fit a model predicting energy consumed per capita (`energy`) from the percentage of residents living in metropolitan areas (`metro`). Be sure to:\n\n1.  Examine/plot the data before fitting the model.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n2.  Print and interpret the model `summary()`.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n3.  Plot the model using `plot()` to look for deviations from modeling assumptions.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n4. Select one or more additional predictors to add to your model and repeat steps 1-3. Is this model significantly better than the model with `metro` as the only predictor?\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Exercise 0 solution\"}\n\nUse the `states` data set. Fit a model predicting energy consumed per capita (`energy`) from the percentage of residents living in metropolitan areas (`metro`). Be sure to:\n\n1.  Examine/plot the data before fitting the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  states_en_met <- states %>% \n      select(energy, metro)\n\n  summary(states_en_met)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     energy          metro       \n Min.   :200.0   Min.   : 20.40  \n 1st Qu.:285.0   1st Qu.: 46.98  \n Median :320.0   Median : 67.55  \n Mean   :354.5   Mean   : 64.07  \n 3rd Qu.:371.5   3rd Qu.: 81.57  \n Max.   :991.0   Max.   :100.00  \n NAs    :1       NAs    :1       \n```\n\n\n:::\n\n```{.r .cell-code}\n  cor(states_en_met, use = \"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           energy      metro\nenergy  1.0000000 -0.3397445\nmetro  -0.3397445  1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\n  qplot(x = metro, y = energy, geom = \"point\", data = states_en_met)\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n2.  Print and interpret the model `summary()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_en_met <- lm(energy ~ metro, data = states_en_met)\n  summary(mod_en_met)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = energy ~ metro, data = states_en_met)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-215.51  -64.54  -30.87   18.71  583.97 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 501.0292    61.8136   8.105 1.53e-10 ***\nmetro        -2.2871     0.9139  -2.503   0.0158 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 140.2 on 48 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.1154,\tAdjusted R-squared:  0.097 \nF-statistic: 6.263 on 1 and 48 DF,  p-value: 0.01578\n```\n\n\n:::\n:::\n\n\n3.  Plot the model using `plot()` to look for deviations from modeling assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  par(mfrow = c(2, 2))\n\n  plot(mod_en_met)\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n4. Select one or more additional predictors to add to your model and repeat steps 1-3. Is this model significantly better than the model with `metro` as the only predictor?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  states_en_met_pop_wst <- states %>%\n      select(energy, metro, pop, waste)\n\n  summary(states_en_met_pop_wst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     energy          metro             pop               waste       \n Min.   :200.0   Min.   : 20.40   Min.   :  454000   Min.   :0.5400  \n 1st Qu.:285.0   1st Qu.: 46.98   1st Qu.: 1299750   1st Qu.:0.8225  \n Median :320.0   Median : 67.55   Median : 3390500   Median :0.9600  \n Mean   :354.5   Mean   : 64.07   Mean   : 4962040   Mean   :0.9888  \n 3rd Qu.:371.5   3rd Qu.: 81.57   3rd Qu.: 5898000   3rd Qu.:1.1450  \n Max.   :991.0   Max.   :100.00   Max.   :29760000   Max.   :1.5100  \n NAs    :1       NAs    :1        NAs    :1          NAs    :1       \n```\n\n\n:::\n\n```{.r .cell-code}\n  cor(states_en_met_pop_wst, use = \"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           energy      metro        pop      waste\nenergy  1.0000000 -0.3397445 -0.1840357 -0.2526499\nmetro  -0.3397445  1.0000000  0.5653562  0.4877881\npop    -0.1840357  0.5653562  1.0000000  0.5255713\nwaste  -0.2526499  0.4877881  0.5255713  1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\n  mod_en_met_pop_waste <- lm(energy ~ 1 + metro + pop + waste, data = states_en_met_pop_wst)\n  summary(mod_en_met_pop_waste)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = energy ~ 1 + metro + pop + waste, data = states_en_met_pop_wst)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-224.62  -67.48  -31.76   12.65  589.48 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  5.617e+02  9.905e+01   5.671    9e-07 ***\nmetro       -2.079e+00  1.168e+00  -1.780   0.0816 .  \npop          1.649e-06  4.809e-06   0.343   0.7332    \nwaste       -8.307e+01  1.042e+02  -0.797   0.4295    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 142.2 on 46 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.1276,\tAdjusted R-squared:  0.07067 \nF-statistic: 2.242 on 3 and 46 DF,  p-value: 0.09599\n```\n\n\n:::\n\n```{.r .cell-code}\n  anova(mod_en_met, mod_en_met_pop_waste)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: energy ~ metro\nModel 2: energy ~ 1 + metro + pop + waste\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1     48 943103                           \n2     46 930153  2     12949 0.3202 0.7276\n```\n\n\n:::\n:::\n\n\n:::\n\n## Interactions & factors\n\n::: {.callout-note}\n\n**GOAL: To learn how to specify interaction effects and fit models with categorical predictors.** In particular:\n\n1. Formula syntax for interaction effects\n2. Factor levels and labels\n3. Contrasts and pairwise comparisons\n\n:::\n\n### Modeling interactions\n\nInteractions allow us assess the extent to which the association between one predictor and the outcome depends on a second predictor. For example: does the association between expense and SAT scores depend on the median income in the state?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # add the interaction to a model\n  sat_expense_by_income <- lm(csat ~ 1 + expense + income + expense : income, data = states)\n\n  # same as above, but shorter syntax\n  sat_expense_by_income <- lm(csat ~ 1 + expense * income, data = states) \n\n  # show the regression coefficients table\n  summary(sat_expense_by_income) %>% coef() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)     1.380364e+03 1.720863e+02  8.021351 2.367069e-10\nexpense        -6.384067e-02 3.270087e-02 -1.952262 5.687837e-02\nincome         -1.049785e+01 4.991463e+00 -2.103161 4.083253e-02\nexpense:income  1.384647e-03 8.635529e-04  1.603431 1.155395e-01\n```\n\n\n:::\n:::\n\n\n### Regression with categorical predictors\n\nLet's try to predict SAT scores (`csat`) from geographical region (`region`), a categorical variable. Note that you must make sure R does not think your categorical variable is numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # make sure R knows region is categorical\n  str(states$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Factor w/ 4 levels \"West\",\"N. East\",..: 3 1 1 3 1 1 2 3 NA 3 ...\n```\n\n\n:::\n:::\n\n\nHere, R is already treating `region` as categorical --- that is, in R parlance, a \"factor\" variable. If `region` were not already a factor, we could make it so like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # convert `region` to a factor\n  states <- states %>%\n      mutate(region = factor(region))\n\n  # arguments to the factor() function:\n  # factor(x, levels, labels)\n\n  # examine factor levels\n  levels(states$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"West\"    \"N. East\" \"South\"   \"Midwest\"\n```\n\n\n:::\n:::\n\n\nNow let's add `region` to the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # add region to the model\n  sat_region <- lm(csat ~ 1 + region, data = states) \n\n  # show the results\n  summary(sat_region) %>% coef() # show only the regression coefficients table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error    t value     Pr(>|t|)\n(Intercept)   946.30769   14.79582 63.9577807 1.352577e-46\nregionN. East -56.75214   23.13285 -2.4533141 1.800383e-02\nregionSouth   -16.30769   19.91948 -0.8186806 4.171898e-01\nregionMidwest  63.77564   21.35592  2.9863209 4.514152e-03\n```\n\n\n:::\n:::\n\n\nWe can get an omnibus F-test for `region` by using the `anova()` method:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  anova(sat_region) # show ANOVA table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: csat\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nregion     3  82049 27349.8  9.6102 4.859e-05 ***\nResiduals 46 130912  2845.9                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nSo, make sure to tell R which variables are categorical by converting them to factors!\n\n### Setting factor reference groups & contrasts\n\n**Contrasts** is the umbrella term used to describe the process of testing linear combinations of parameters from regression models. All statistical sofware use contrasts, but each software has different defaults and their own way of overriding these.\n\nThe default contrasts in R are \"treatment\" contrasts (aka \"dummy coding\"), where each level within a factor is identified within a matrix of binary `0` / `1` variables, with the first level chosen as the reference category. They're called \"treatment\" contrasts, because of the typical use case where there is one control group (the reference group) and one or more treatment groups that are to be compared to the controls. It is easy to change the default contrasts to something other than treatment contrasts, though this is rarely needed. More often, we may want to change the reference group in treatment contrasts or get all sets of pairwise contrasts between factor levels.\n\nFirst, let's examine the default contrasts for `region`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # default treatment (dummy) contrasts\n  contrasts(states$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        N. East South Midwest\nWest          0     0       0\nN. East       1     0       0\nSouth         0     1       0\nMidwest       0     0       1\n```\n\n\n:::\n:::\n\n\nWe can see that the reference level is `West`. How can we change this? Let's use the `relevel()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # change the reference group\n  states <- states %>%\n      mutate(region = relevel(region, ref = \"Midwest\"))\n\n  # check the reference group has changed\n  contrasts(states$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        West N. East South\nMidwest    0       0     0\nWest       1       0     0\nN. East    0       1     0\nSouth      0       0     1\n```\n\n\n:::\n:::\n\n\nNow the reference level has changed to `Midwest`. Let's refit the model with the releveled `region` variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # refit the model\n  mod_region <- lm(csat ~ 1 + region, data = states)\n\n  # print summary coefficients table\n  summary(mod_region) %>% coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error   t value     Pr(>|t|)\n(Intercept)   1010.08333   15.39998 65.589930 4.296307e-47\nregionWest     -63.77564   21.35592 -2.986321 4.514152e-03\nregionN. East -120.52778   23.52385 -5.123641 5.798399e-06\nregionSouth    -80.08333   20.37225 -3.931000 2.826007e-04\n```\n\n\n:::\n:::\n\n\nOften, we may want to get all possible pairwise comparisons among the various levels of a factor variable, rather than just compare particular levels to a single reference level. We could of course just keep changing the reference level and refitting the model, but this would be tedious. Instead, we can use the `emmeans()` post-estimation function from the `emmeans` package to do the calculations for us:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # get all pairwise contrasts between means\n  mod_region %>%\n      emmeans(specs = pairwise ~ region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n region  emmean   SE df lower.CL upper.CL\n Midwest   1010 15.4 46      979     1041\n West       946 14.8 46      917      976\n N. East    890 17.8 46      854      925\n South      930 13.3 46      903      957\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast          estimate   SE df t.ratio p.value\n Midwest - West        63.8 21.4 46   2.986  0.0226\n Midwest - N. East    120.5 23.5 46   5.124 <0.0001\n Midwest - South       80.1 20.4 46   3.931  0.0016\n West - N. East        56.8 23.1 46   2.453  0.0812\n West - South          16.3 19.9 46   0.819  0.8453\n N. East - South      -40.4 22.2 46  -1.820  0.2774\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n### Exercise 1\n\n**Interactions & factors**\n\nUse the `states` data set.\n\n1.  Add on to the regression equation that you created in Exercise 1 by generating an interaction term and testing the interaction.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n2.  Try adding `region` to the model. Are there significant differences across the four regions?\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Exercise 1 solution\"}\n\nUse the `states` data set.\n\n1.  Add on to the regression equation that you created in exercise 1 by generating an interaction term and testing the interaction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_en_metro_by_waste <- lm(energy ~ 1 + metro * waste, data = states)\n```\n:::\n\n\n2.  Try adding `region` to the model. Are there significant differences across the four regions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_en_region <- lm(energy ~ 1 + metro * waste + region, data = states)\n  anova(mod_en_metro_by_waste, mod_en_region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: energy ~ 1 + metro * waste\nModel 2: energy ~ 1 + metro * waste + region\n  Res.Df    RSS Df Sum of Sq    F Pr(>F)\n1     46 930683                         \n2     43 821247  3    109436 1.91 0.1422\n```\n\n\n:::\n:::\n\n\n:::\n\n## Models with binary outcomes\n\n::: {.callout-note}\n\n**GOAL: To learn how to use the `glm()` function to model binary outcomes.** In particular:\n\n1. The `family` and `link` components of the `glm()` function call\n2. Transforming model coefficients into odds ratios\n3. Transforming model coefficients into predicted marginal means\n\n:::\n\n### Logistic regression\n\nThus far we have used the `lm()` function to fit our regression models. `lm()` is great, but limited --- in particular it only fits models for continuous dependent variables. For categorical dependent variables we can use the `glm()` function.\n\nFor these models we will use a different dataset, drawn from the National Health Interview Survey. From the [CDC website](http://www.cdc.gov/nchs/nhis.htm):\n\n> The National Health Interview Survey (NHIS) has monitored the health of the nation since 1957. NHIS data on a broad range of health topics are collected through personal household interviews. For over 50 years, the U.S. Census Bureau has been the data collection agent for the National Health Interview Survey. Survey results have been instrumental in providing data to track health status, health care access, and progress toward achieving national health objectives.\n\nLoad the National Health Interview Survey data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  NH11 <- read_rds(\"dataSets/NatHealth2011.rds\")\n```\n:::\n\n\n### Logistic regression example\n\nIf we were to use a linear model, rather than a logistic model, when we have a binary response we would find that:\n\n1. Explanatory variables will not be linearly related to the outcome\n2. Residuals will not be normally distributed\n3. Variance will not be homoskedastic\n4. Predictions will not be constrained to be on the interval [0, 1]\n\nThough, some of these issues can be dealt with by estimating a linear probability model with robust standard errors.\n\n![](images/models/logistic.png)\n\nAnatomy of a generalized linear model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # OLS model using lm()\n  lm(outcome ~ 1 + pred1 + pred2, \n     data = mydata)\n\n  # OLS model using glm()\n  glm(outcome ~ 1 + pred1 + pred2, \n      data = mydata, \n      family = gaussian(link = \"identity\"))\n \n  # logistic model using glm()\n  glm(outcome ~ 1 + pred1 + pred2, \n      data = mydata, \n      family = binomial(link = \"logit\"))\n```\n:::\n\n\nThe `family` argument sets the error distribution for the model, while the `link` function argument relates the predictors to the expected value of the outcome.\n\nLet's predict the probability of being diagnosed with hypertension based on age, sex, sleep, and bmi. Here's the theoretical model:\n\n::: {.callout-note}\n\n$$\nlogit(p(hypertension_i = 1)) = \\beta_{0}1 + \\beta_1age_i + \\beta_2sex_i + \\beta_3sleep_i + \\beta_4bmi_i \n$$\n\n:::\n\nwhere $logit(\\cdot)$ is the non-linear link function that relates a linear expression of the predictors to the expectation of the binary response:\n\n::: {.callout-note}\n\n$$\nlogit(p(hypertension_i = 1)) = ln \\left( \\frac{p(hypertension_i = 1)}{1-p(hypertension_i = 1)} \\right) = ln \\left( \\frac{p(hypertension_i = 1)}{p(hypertension_i = 0)} \\right)\n$$\n\n:::\n\nAnd here's how we fit this model in R. First, let's clean up the hypertension outcome by making it binary:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  str(NH11$hypev) # check stucture of hypev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Factor w/ 5 levels \"1 Yes\",\"2 No\",..: 2 2 1 2 2 1 2 2 1 2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n  levels(NH11$hypev) # check levels of hypev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1 Yes\"             \"2 No\"              \"7 Refused\"        \n[4] \"8 Not ascertained\" \"9 Don't know\"     \n```\n\n\n:::\n\n```{.r .cell-code}\n  # collapse all missing values to NA\n  NH11 <- NH11 %>%\n      mutate(hypev = factor(hypev, levels=c(\"2 No\", \"1 Yes\")))\n```\n:::\n\n\nNow let's use `glm()` to estimate the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # run our regression model\n  hyp_out <- glm(hypev ~ 1 + age_p + sex + sleep + bmi,\n                 data = NH11, \n                 family = binomial(link = \"logit\"))\n  \n  # summary model coefficients table\n  summary(hyp_out) %>% coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Std. Error    z value     Pr(>|z|)\n(Intercept) -4.269466028 0.0564947294 -75.572820 0.000000e+00\nage_p        0.060699303 0.0008227207  73.778743 0.000000e+00\nsex2 Female -0.144025092 0.0267976605  -5.374540 7.677854e-08\nsleep       -0.007035776 0.0016397197  -4.290841 1.779981e-05\nbmi          0.018571704 0.0009510828  19.526906 6.485172e-85\n```\n\n\n:::\n:::\n\n\n### Odds ratios\n\nGeneralized linear models use link functions to relate the average value of the response to the predictors, so raw coefficients are difficult to interpret. For example, the `age` coefficient of 0.06 in the previous model tells us that for every one unit increase in `age`, the log odds of hypertension diagnosis increases by 0.06. Since most of us are not used to thinking in log odds this is not too helpful!\n\nOne solution is to transform the coefficients to make them easier to interpret. Here we transform them into odds ratios by exponentiating:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # point estimates\n  coef(hyp_out) %>% exp()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       age_p sex2 Female       sleep         bmi \n 0.01398925  1.06257935  0.86586602  0.99298892  1.01874523 \n```\n\n\n:::\n\n```{.r .cell-code}\n  # confidence intervals\n  confint(hyp_out) %>% exp()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 0.01251677 0.01561971\nage_p       1.06087385 1.06430082\nsex2 Female 0.82155196 0.91255008\nsleep       0.98978755 0.99617465\nbmi         1.01685145 1.02065009\n```\n\n\n:::\n:::\n\n\n### Predicted marginal means\n\nInstead of reporting odds ratios, we may want to calculate predicted marginal means (sometimes called \"least-squares means\" or \"estimated marginal means\"). These are average values of the outcome at particular levels of the predictors. For ease of interpretation, we want these marginal means to be on the response scale (i.e., the probability scale). We can use the `effects` package to compute these quantities of interest for us (by default, the numerical output will be on the response scale).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # get predicted marginal means\n  hyp_out %>% \n      allEffects() %>%\n      plot(type = \"response\") # \"response\" refers to the probability scale\n```\n\n::: {.cell-output-display}\n![](models_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nBy default, `allEffects()` will produce predictions for all levels of factor variables, while for continuous variables it will chose 5 representative values based on quantiles. We can easily override this behavior using the `xlevels` argument and get predictions at any values of a continuous variable. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # generate a sequence of ages at which to get predictions of the outcome\n  age_years <- seq(20, 80, by = 5)\n  age_years\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 20 25 30 35 40 45 50 55 60 65 70 75 80\n```\n\n\n:::\n\n```{.r .cell-code}\n  # get predicted marginal means\n  eff_df <- \n      hyp_out %>% \n      allEffects(xlevels = list(age_p = age_years)) %>% # override defaults for age\n      as.data.frame() # get confidence intervals\n  \n  eff_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$age_p\n   age_p        fit          se      lower      upper\n1     20 0.06690384 0.001915704 0.06324553 0.07075778\n2     25 0.08852692 0.002181618 0.08434323 0.09289708\n3     30 0.11626770 0.002418813 0.11161020 0.12109307\n4     35 0.15125876 0.002603243 0.14622690 0.15643204\n5     40 0.19446321 0.002722428 0.18918282 0.19985467\n6     45 0.24642528 0.002796260 0.24098582 0.25194677\n7     50 0.30698073 0.002895857 0.30133437 0.31268554\n8     55 0.37501156 0.003124112 0.36890868 0.38115441\n9     60 0.44836479 0.003531792 0.44145305 0.45529654\n10    65 0.52403564 0.004052454 0.51608756 0.53197156\n11    70 0.59861876 0.004545531 0.58967801 0.60749436\n12    75 0.66889903 0.004880732 0.65926418 0.67839434\n13    80 0.73237506 0.004986539 0.72248912 0.74203457\n\n$sex\n       sex       fit          se     lower     upper\n1   1 Male 0.2994186 0.004188707 0.2912739 0.3076922\n2 2 Female 0.2701044 0.003715028 0.2628852 0.2774472\n\n$sleep\n  sleep       fit          se     lower     upper\n1     3 0.2899941 0.003276427 0.2836147 0.2964575\n2    30 0.2524895 0.007427001 0.2382124 0.2673219\n3    50 0.2268657 0.012446183 0.2034008 0.2521806\n4    80 0.1919843 0.018549461 0.1582199 0.2309771\n5   100 0.1710955 0.021584286 0.1328287 0.2176200\n\n$bmi\n  bmi       fit          se     lower     upper\n1  10 0.2144084 0.004121590 0.2064409 0.2225972\n2  30 0.2835093 0.002849407 0.2779580 0.2891272\n3  60 0.4085485 0.007450161 0.3940311 0.4232272\n4  80 0.5003663 0.012139141 0.4765911 0.5241398\n5 100 0.5921593 0.016180071 0.5601051 0.6234481\n```\n\n\n:::\n:::\n\n\n### Exercise 2 \n\n**Logistic regression**\n\nUse the `NH11` data set that we loaded earlier. Note that the data are not perfectly clean and ready to be modeled. You will need to clean up at least some of the variables before fitting the model.\n\n1.  Use `glm()` to conduct a logistic regression to predict ever worked (`everwrk`) using age (`age_p`) and marital status (`r_maritl`). Make sure you only keep the following two levels for `everwrk` (`2 No` and `1 Yes`). Hint: use the `factor()` function. Also, make sure to drop any `r_maritl` levels that do not contain observations. Hint: see `?droplevels`.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n2.  Predict the probability of working for each level of marital status. Hint: use `allEffects()`\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\nNote that the data are not perfectly clean and ready to be modeled. You will need to clean up at least some of the variables before fitting the model.\n\n::: {.callout-tip collapse=\"true\" title=\"Exercise 2 solution\"}\n\nUse the `NH11` data set that we loaded earlier. Note that the data are not perfectly clean and ready to be modeled. You will need to clean up at least some of the variables before fitting the model.\n\n1.  Use `glm()` to conduct a logistic regression to predict ever worked (`everwrk`) using age (`age_p`) and marital status (`r_maritl`). Make sure you only keep the following two levels for `everwrk` (`2 No` and `1 Yes`). Hint: use the `factor()` function. Also, make sure to drop any `r_maritl` levels that do not contain observations. Hint: see `?droplevels`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  NH11 <- NH11 %>%\n      mutate(everwrk = factor(everwrk, levels = c(\"2 No\", \"1 Yes\")),\n             r_maritl = droplevels(r_maritl)\n             )\n\n  mod_wk_age_mar <- glm(everwrk ~ 1 + age_p + r_maritl, \n                        data = NH11,\n                        family = binomial(link = \"logit\"))\n\n  summary(mod_wk_age_mar)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = everwrk ~ 1 + age_p + r_maritl, family = binomial(link = \"logit\"), \n    data = NH11)\n\nCoefficients:\n                                             Estimate Std. Error z value\n(Intercept)                                  0.440248   0.093538   4.707\nage_p                                        0.029812   0.001645  18.118\nr_maritl2 Married - spouse not in household -0.049675   0.217310  -0.229\nr_maritl4 Widowed                           -0.683618   0.084335  -8.106\nr_maritl5 Divorced                           0.730115   0.111681   6.538\nr_maritl6 Separated                          0.128091   0.151366   0.846\nr_maritl7 Never married                     -0.343611   0.069222  -4.964\nr_maritl8 Living with partner                0.443583   0.137770   3.220\nr_maritl9 Unknown marital status            -0.395480   0.492967  -0.802\n                                            Pr(>|z|)    \n(Intercept)                                 2.52e-06 ***\nage_p                                        < 2e-16 ***\nr_maritl2 Married - spouse not in household  0.81919    \nr_maritl4 Widowed                           5.23e-16 ***\nr_maritl5 Divorced                          6.25e-11 ***\nr_maritl6 Separated                          0.39742    \nr_maritl7 Never married                     6.91e-07 ***\nr_maritl8 Living with partner                0.00128 ** \nr_maritl9 Unknown marital status             0.42241    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 11082  on 14039  degrees of freedom\nResidual deviance: 10309  on 14031  degrees of freedom\n  (18974 observations deleted due to missingness)\nAIC: 10327\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n2.  Predict the probability of working for each level of marital status. Hint: use `allEffects()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_wk_age_mar %>% \n      allEffects() %>%\n      as.data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$age_p\n  age_p       fit          se     lower     upper\n1    20 0.7241256 0.011448539 0.7011322 0.7459909\n2    30 0.7795664 0.007483648 0.7645495 0.7938837\n3    50 0.8652253 0.003183752 0.8588624 0.8713443\n4    70 0.9209721 0.003053617 0.9147761 0.9267537\n5    80 0.9401248 0.003123927 0.9337009 0.9459624\n\n$r_maritl\n                             r_maritl       fit          se     lower     upper\n1     1 Married - spouse in household 0.8917800 0.004259644 0.8831439 0.8998502\n2 2 Married - spouse not in household 0.8868918 0.021393167 0.8377247 0.9225394\n3                           4 Widowed 0.8061891 0.010634762 0.7844913 0.8261864\n4                          5 Divorced 0.9447561 0.005361664 0.9332564 0.9543712\n5                         6 Separated 0.9035358 0.012707502 0.8755978 0.9257318\n6                     7 Never married 0.8538900 0.007459212 0.8386559 0.8679122\n7               8 Living with partner 0.9277504 0.008904955 0.9082334 0.9433753\n8            9 Unknown marital status 0.8472992 0.063528455 0.6794427 0.9355916\n```\n\n\n:::\n:::\n\n\n:::\n\n## Multilevel modeling\n\n::: {.callout-note}\n\n**GOAL: To learn about how to use the `lmer()` function to model clustered data.** In particular:\n\n1. The formula syntax for incorporating random effects into a model\n2. Calculating the intraclass correlation (ICC)\n3. Model comparison for fixed and random effects\n\n:::\n\n### Multilevel modeling overview\n\n* Multi-level (AKA hierarchical) models are a type of **mixed-effects** model\n* They are used to model data that are clustered (i.e., non-independent)\n* Mixed-effects models include two types of predictors: **fixed-effects** and **random effects**\n  + **Fixed-effects** -- observed levels are of direct interest (.e.g, sex, political party...)\n  + **Random-effects** -- observed levels not of direct interest: goal is to make inferences to a population represented by observed levels\n  + In R, the `lme4` package is the most popular for mixed effects models\n  + Use the `lmer()` function for linear mixed models, `glmer()` for generalized linear mixed models\n\n### The Exam data\n\nThe `Exam.rds` data set contains exam scores of 4,059 students from 65 schools in Inner London. The variable names are as follows:\n\n| Variable | Description                             |\n|:---------|:----------------------------------------|\n| school   | School ID - a factor.                   |\n| normexam | Normalized exam score.                  |\n| standLRT | Standardized LR test score.             |\n| student  | Student id (within school) - a factor   |\n\nLet's read in the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  exam <- read_rds(\"dataSets/Exam.rds\")\n```\n:::\n\n\n### The null model & ICC\n\nBefore we fit our first model, let's take a look at the R syntax for multilevel models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # anatomy of lmer() function\n  lmer(outcome ~ 1 + pred1 + pred2 + (1 | grouping_variable), \n       data = mydata)\n```\n:::\n\n\nNotice the formula section within the brackets: `(1 | grouping_variable)`. This part of the formula tells R about the hierarchical structure of the model. In this case, it says we have a model with random intercepts (`1`) grouped by (`|`) a `grouping_variable`.\n\nAs a preliminary modeling step, it is often useful to partition the variance in the dependent variable into the various levels. This can be accomplished by running a null model (i.e., a model with a random effects grouping structure, but no fixed-effects predictors) and then calculating the intra-class correlation (ICC).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # null model, grouping by school but not fixed effects.\n  Norm1 <-lmer(normexam ~ 1 + (1 | school), \n               data = na.omit(exam))\n  summary(Norm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: normexam ~ 1 + (1 | school)\n   Data: na.omit(exam)\n\nREML criterion at convergence: 9962.9\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.8749 -0.6452  0.0045  0.6888  3.6836 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n school   (Intercept) 0.1634   0.4042  \n Residual             0.8520   0.9231  \nNumber of obs: 3662, groups:  school, 65\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) -0.01310    0.05312  -0.247\n```\n\n\n:::\n:::\n\n\nThe ICC is calculated as .163/(.163 + .852) = .161, which means that ~16% of the variance is at the school level. \n\nThere is no consensus on how to calculate p-values for MLMs; hence why they are omitted from the `lme4` output. But, if you really need p-values, the `lmerTest` package will calculate p-values for you (using the Satterthwaite approximation).\n\n### Adding fixed-effects predictors\n\nHere's a theoretical model that predicts exam scores from student's standardized tests scores:\n\n::: {.callout-note}\n\n$$\nexamscores_{ij} = \\mu1 + \\beta_1testscores_{ij} + U_{0j} + \\epsilon_{ij}\n$$\n\n:::\n\nwhere $U_{0j}$ is the random intercept for the $j$<sup>th</sup> `school`. Let's implement this in R using `lmer()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # model with exam scores regressed on student's standardized tests scores\n  Norm2 <-lmer(normexam ~ 1 + standLRT + (1 | school),\n               data = na.omit(exam)) \n  summary(Norm2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: normexam ~ 1 + standLRT + (1 | school)\n   Data: na.omit(exam)\n\nREML criterion at convergence: 8483.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.6725 -0.6300  0.0234  0.6777  3.3340 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n school   (Intercept) 0.09369  0.3061  \n Residual             0.56924  0.7545  \nNumber of obs: 3662, groups:  school, 65\n\nFixed effects:\n              Estimate Std. Error t value\n(Intercept) -4.313e-05  4.055e-02  -0.001\nstandLRT     5.669e-01  1.324e-02  42.821\n\nCorrelation of Fixed Effects:\n         (Intr)\nstandLRT 0.007 \n```\n\n\n:::\n:::\n\n\n### Multiple degree of freedom comparisons\n\nAs with `lm()` and `glm()` models, you can compare the two `lmer()` models using the `anova()` function. With mixed effects models, this will produce a likelihood ratio test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # likelihood ratio test of two nested models\n  anova(Norm1, Norm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: na.omit(exam)\nModels:\nNorm1: normexam ~ 1 + (1 | school)\nNorm2: normexam ~ 1 + standLRT + (1 | school)\n      npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nNorm1    3 9964.9 9983.5 -4979.4    9958.9                         \nNorm2    4 8480.1 8505.0 -4236.1    8472.1 1486.8  1  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Random slopes\n\nWe can add a random effect of students' standardized test scores as well. Now in addition to estimating the distribution of intercepts across schools, we also estimate the distribution of the slope of exam on standardized test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # add random effect of students' standardized test scores to model\n  Norm3 <- lmer(normexam ~ 1 + standLRT + (1 + standLRT | school), \n                data = na.omit(exam)) \n  summary(Norm3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: normexam ~ 1 + standLRT + (1 + standLRT | school)\n   Data: na.omit(exam)\n\nREML criterion at convergence: 8442.8\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.7904 -0.6246  0.0245  0.6734  3.4376 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n school   (Intercept) 0.09092  0.3015        \n          standLRT    0.01639  0.1280   0.49 \n Residual             0.55589  0.7456        \nNumber of obs: 3662, groups:  school, 65\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) -0.01250    0.04011  -0.312\nstandLRT     0.56094    0.02119  26.474\n\nCorrelation of Fixed Effects:\n         (Intr)\nstandLRT 0.360 \n```\n\n\n:::\n:::\n\n\n### Test the significance of the random slope\n\nTo test the significance of a random slope just compare models with and without the random slope term using a likelihood ratio test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # likelihood ratio test for random slope term\n  anova(Norm2, Norm3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: na.omit(exam)\nModels:\nNorm2: normexam ~ 1 + standLRT + (1 | school)\nNorm3: normexam ~ 1 + standLRT + (1 + standLRT | school)\n      npar    AIC    BIC  logLik -2*log(L) Chisq Df Pr(>Chisq)    \nNorm2    4 8480.1 8505.0 -4236.1    8472.1                        \nNorm3    6 8444.1 8481.4 -4216.1    8432.1 40.01  2  2.051e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Exercise 3\n\n**Multilevel modeling**\n\nUse the `bh1996` dataset: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n## install.packages(\"multilevel\")\ndata(bh1996, package = \"multilevel\")\n```\n:::\n\n\nFrom the data documentation:\n\n> Variables are Leadership Climate (`LEAD`), Well-Being (`WBEING`), and Work Hours (`HRS`). The group identifier is named `GRP`.\n\n1.  Create a null model predicting wellbeing (`WBEING`)\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n2.  Calculate the ICC for your null model\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n3.  Run a second multi-level model that adds two individual-level predictors, average number of hours worked (`HRS`) and leadership skills (`LEAD`) to the model and interpret your output.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n4.  Now, add a random effect of average number of hours worked (`HRS`) to the model and interpret your output. Test the significance of this random term.\n\n::: {.cell}\n\n```{.r .cell-code}\n## \n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Exercise 3 solution\"}\n\nUse the dataset `bh1996`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  # install.packages(\"multilevel\")\n  data(bh1996, package=\"multilevel\")\n```\n:::\n\n\nFrom the data documentation:\n\n> Variables are Leadership Climate (`LEAD`), Well-Being (`WBEING`), and Work Hours (`HRS`). The group identifier is named `GRP`.\n\n1.  Create a null model predicting wellbeing (`WBEING`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_grp0 <- lmer(WBEING ~ 1 + (1 | GRP), data = na.omit(bh1996))\n  summary(mod_grp0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: WBEING ~ 1 + (1 | GRP)\n   Data: na.omit(bh1996)\n\nREML criterion at convergence: 19347.3\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3217 -0.6475  0.0311  0.7182  2.6674 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n GRP      (Intercept) 0.0358   0.1892  \n Residual             0.7895   0.8885  \nNumber of obs: 7382, groups:  GRP, 99\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)   2.7743     0.0222   124.9\n```\n\n\n:::\n:::\n\n\n2.  Calculate the ICC for your null model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  0.0358 / (0.0358 + 0.7895)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04337817\n```\n\n\n:::\n:::\n\n\n3.  Run a second multi-level model that adds two individual-level predictors, average number of hours worked (`HRS`) and leadership skills (`LEAD`) to the model and interpret your output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_grp1 <- lmer(WBEING ~ 1 + HRS + LEAD + (1 | GRP), data = na.omit(bh1996))\n  summary(mod_grp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: WBEING ~ 1 + HRS + LEAD + (1 | GRP)\n   Data: na.omit(bh1996)\n\nREML criterion at convergence: 17860\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.9188 -0.6588  0.0382  0.7040  3.6440 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n GRP      (Intercept) 0.01929  0.1389  \n Residual             0.64668  0.8042  \nNumber of obs: 7382, groups:  GRP, 99\n\nFixed effects:\n             Estimate Std. Error t value\n(Intercept)  1.686160   0.067702  24.906\nHRS         -0.031617   0.004378  -7.221\nLEAD         0.500743   0.012811  39.087\n\nCorrelation of Fixed Effects:\n     (Intr) HRS   \nHRS  -0.800       \nLEAD -0.635  0.121\n```\n\n\n:::\n:::\n\n\n4.  Now, add a random effect of average number of hours worked (`HRS`) to the model and interpret your output. Test the significance of this random term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  mod_grp2 <- lmer(WBEING ~ 1 + HRS + LEAD + (1 + HRS | GRP), data = na.omit(bh1996))\n  anova(mod_grp1, mod_grp2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: na.omit(bh1996)\nModels:\nmod_grp1: WBEING ~ 1 + HRS + LEAD + (1 | GRP)\nmod_grp2: WBEING ~ 1 + HRS + LEAD + (1 + HRS | GRP)\n         npar   AIC   BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)\nmod_grp1    5 17848 17882 -8918.9     17838                     \nmod_grp2    7 17851 17899 -8918.3     17837 1.2202  2     0.5433\n```\n\n\n:::\n:::\n\n\n:::\n\n## Wrap-up\n\n### Feedback\n\nThese workshops are a work in progress, please provide any feedback to: help@iq.harvard.edu\n\n### Resources\n\n* IQSS \n    + Workshops: <https://www.iq.harvard.edu/data-science-services/workshop-materials>\n    + Data Science Services: <https://www.iq.harvard.edu/data-science-services>\n    + Research Computing Environment: <https://iqss.github.io/dss-rce/>\n\n* HBS\n    + Research Computing Services workshops: <https://training.rcs.hbs.org/workshops>\n    + Other HBS RCS resources: <https://training.rcs.hbs.org/workshop-materials>\n    + RCS consulting email: <mailto:research@hbs.edu>\n",
    "supporting": [
      "models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}