---
title: "Data Science Tools"
format: html
---

**Topics**

* Data science tool selection
* Data analysis pipelines
* Programming languages comparison
* Text editor and IDE comparison
* Tools for creating reports

## Tools for working with data

Working with data effectively requires learning at least one programming or scripting language. You can get by without this, but it would be like trying to cook with only a butter knife; not recommended! Compared to using a menu-driven interface (e.g., SPSS or SAS) or a spreadsheet (e.g., Excel), using a programming language allows you to:

* reproduce results,
* correct errors and update output,
* reuse code,
* collaborate with others,
* automate repetitive tasks, and
* generate manuscripts, reports, and other documents from your code.

So, you need to learn a programming language for working with data, but which one should you learn? Since you'll be writing code you'll want to set up a comfortable environment for writing and editing that code. Which text editors are good for this? You'll probably also want to learn at least one markup language (e.g., LaTeX, Markdown) so that you can create reproducible manuscripts. What tools are good for this? These questions will guide our discussion, the goal of which is to help you decide which tools you should invest time in learning.

## The puzzle pieces

As we've noted, working effectively with data requires using a number of tools.

### Data analysis building blocks

The basic pieces are:

* a data storage and retrieval system,
* an editor for writing code,
* an interpreter or compiler for executing that code,
* a system for presenting results, and
* some "glue" to make all the pieces work together.

## Examples

Before looking in detail at each of these building blocks we'll look at a few examples to get an intuitive feel for the basic elements.

### Old-school example

In this example we're going to process data in a text file in a way that would be familiar to a statistician working forty years ago. Surprisingly, it's not much different from the way we would do it today. Programs come and go, but the basic ideas remain pretty much the same!

Specifically, we'll process the data in `1980_census.txt` by writing **fortran** code in the **vi** text editor and running it through the **fortran** compiler. Then we'll take the results and put them in to a **TeX** file, again using the **vi** editor to create the report. For "glue" we will use a terminal emulator running the bash shell. All of these tools were available in 1980, though some features have been added since that time.

| example    | data storage    | editor | program | report tool | glue                      |
|:---------- |:--------------- |:------ |:------- |:----------- |:------------------------- |
| old school | ASCII text file | vi     | fortran | TeX         | Bourne (compatible) shell |

### Something old & something new

Next we're going to do the same basic process, this time using a modern text editor (**Atom**), a different programming language (**Python**), and a modern report generation system (**LaTeX** processed via **XeLaTeX**). For the glue we're still going to use a shell.

| example     | data storage    | editor | program | report tool | glue                      |
|:----------- |:--------------- |:------ |:------- |:----------- |:------------------------- |
| old school  | ASCII text file | vi     | fortran | TeX         | Bourne (compatible) shell |
| old and new | ASCII text file | Atom   | python  | LaTeX       | Bash shell                |

### A modern version

Finally, we'll produce the same report using modern tools. Remember, the process is basically the same: we're just using different tools.

| example     | data storage    | editor  | program | report tool | glue                      |
|:----------- |:--------------- |:------- |:------- |:----------- |:------------------------- |
| old school  | ASCII text file | vi      | fortran | TeX         | Bourne (compatable) shell |
| old and new | ASCII text file | Atom    | python  | LaTeX       | Bash shell                |
| modern      | SQLite database | Rstudio | R       | R Markdown  | Rstudio                   |

## Data storage & retrieval

Data storage and retrieval is a fairly dry topic, so we won't spend too much time on it. There are roughly four types of technology for storing and retrieving data.

### Text files

Storing data in text files (e.g., comma separated values, other delimited text formats) is simple and makes the data easy to access from just about any program. It is also good for archiving data since no specialized software is needed to read it. The main downsides are that retrieval is slow and often all-or-nothing, and the fact that storing metadata in plain text files is cumbersome.

### Binary files

Many statistics packages and programming languages have a "native" binary data storage format. For example, Stata stores data in `.dta` files, and R stores data in `.rds` or `.Rdata` files. These storage formats usually more efficient than text files, and usually provide faster read/write access. They usually include a mechanism for storing metadata. The down side is that specialized software is required to read them (will Stata exist in 50 years? Are you sure?) and the ability to read them using other programs may be limited.

### Databases

Storing data in a database requires more up-front planning and set up, but has several advantages. Databases provide fast selective retrieval and facilitate efficient storage and flexible retrieval.

### Distributed file storage

Data that is too large to fit on a single hard drive may be stored and analyzed on a distributed file system or database such as the *Hadoop Distributed File System* or *Cassandra*. When working with data on this scale considerable infrastructure and specialized tools will be required.

## Programming languages & statistics packages

There are tens of programs for statistics and data science available. Here we will focus only on the more popular programs that offer a wide range of features. Note that for specific applications a specialized program may be better, e.g., many people use Mplus for structural equation models and another program for everything else.

### Programming language features

Things we want a statistics program to do include:

* read/write data from/to a variety of data storage systems,
* manipulate data,
* perform statistical methods,
* visualize data and results,
* export results in a variety of formats,
* be easy to use,
* be well documented,
* have a large user community.

Note that this list is deceptively simple; each item may include a diversity of complicated features. For example,"read/write data from/to a variety of data storage systems" may include reading from databases, image files, .pdf files, .html and .xml files from a website, and any number of proprietary data storage formats.

### Program comparison

| Program | Statistics | Visualization | Machine learning | Ease of use | Power/flexibility | Fun  |
|:------- |:---------- |:------------- |:---------------- |:----------- |:----------------- |:---- |
| Stata   | Excellent  | Servicable    | Limited          | Very easy   | Low               | Some |
| SPSS    | OK         | Servicable    | Limited          | Easy        | Low               | None |
| SAS     | Good       | Not great     | Good             | Moderate    | Moderate          | None |
| Matlab  | Good       | Good          | Good             | Moderate    | Good              | Some |
| R       | Excellent  | Excellent     | Good             | Moderate    | Excellent         | Yes  |
| Python  | Good       | Good          | Excellent        | Moderate    | Excellent         | Yes  |
| Julia   | OK         | Excellent     | Good             | Hard        | Excellent         | Yes  |

## Creating reports

Once you've analyzed your data you'll most likely want to communicate your results. For short informal projects this might take the form of a blog post or an email to your colleagues. For larger more formal projects you'll likely want to prepare a substantial report or manuscript for disseminating your findings via a journal publication or other means. Other common means of reporting research findings include posters or slides for a conference talk.

Regardless of the type of report, you may choose to use either a *markup language* or a WYSIWYG application like Microsoft Word/Powerpoint of a desktop publishing application such as Adobe InDesign.

### Markup languages

A markup language is a system for producing a formatted document from a text file using information by the markup. A major advantage of markup languages is that the formatting instructions can be easily generated by the program you use for analyzing your data.

Markup languages include *HTML*, *LaTeX*, *Markdown* and many others. *LaTeX* and *Markdown* are currently popular among data scientists, although others are used as well.

*Markdown* is easy to write and designed to be human-readable. It is newer and somewhat less feature-full compared to LaTeX. It's main advantage is simplicity. *LaTeX* is more verbose but provides for just about any feature you'll ever need.

### Word processors

Modern word processors are largely just graphical user interfaces that write a markup language (usually XML) for you. They are commonly used for creating reports, but care must be taken when doing so.

If you use a word processor to produce your reports you should

* use the structured outline feature,
* link rather than embed external resources (figures, tables, etc.),
* use cross-referencing features, and
* use a bibliography management system.

## Text editors & Integrated Development Environments

A text editor edits text obviously. But that is not all! At a minimum, a text editor will also have a mechanism for reading and writing text files. Most text editors do much more than this.

An IDE provides tools for working with code, such as syntax highlighting, code completion, jump-to-definition, execute/compile, package management, refactoring, etc. Of course an IDE includes a text editor.

Editors and IDE's are not really separate categories; as you add features to a text editor it becomes more like an IDE, and a simple IDE may provide little more than a text editor. For example, Emacs is commonly referred to as a text editor, but it provides nearly every feature you would expect an IDE to have.

A more useful distinction is between language-specific editors/IDEs and general purpose editors/IDEs. The former are typically easier to set up since they come pre-configured for use with a specific language. General purpose editors/IDEs typically provide language support via *plugins* and may require extensive configuration for each language.

### Language specific editors & IDEs

| Editor               | Features  | Ease of use | Language |
|:-------------------- |:--------- |:----------- |:-------- |
| Positron             | Excellent | Easy        | R, Python |
| RStudio              | Excellent | Easy        | R, Python |
| Spyder               | Excellent | Easy        | Python   |
| Stata do file editor | OK        | Easy        | Stata    |
| SPSS syntax editor   | OK        | Easy        | SPSS     |

### General purpose editors & IDEs

| Editor       | Features  | Ease of use | Language support |
|:------------ |:--------- |:----------- |:---------------- |
| Vim          | Excellent | Hard        | Good             |
| Emacs        | Excellent | Hard        | Excellent        |
| VS Code      | Excellent | Easy        | Very good        |
| Eclipse      | Excellent | Easy        | Good             |
| Sublime Text | Good      | Easy        | Good             |
| Notepad++    | OK        | Easy        | OK               |
| Textmate     | Good      | Moderate    | Good             |
| Kate         | OK        | Easy        | Good             |

## Literate programming & notebooks

In one of the Early demos we say an example of embedding R code in a markdown document. A closely related approach is to create a *notebook* that includes the prose of the report, the code used for the analysis, and the results produced by that code.

### Literate programming

Literate programming is the practice of embedding computer code in a natural language document. For example, using *RMarkdown* we can embed R code in a report authored using Markdown. Python and Stata have their own versions of literate programming using Markdown.

### Notebooks

Notebooks go one step farther, and include the output produced by the original program directly in the notebook. Examples include *Jupyter*, *Appache Zeppelin*, and *Emacs Org Mode*.

## Big data, annoying data, & computationally intensive methods

Thus far we've discussed popular programming languages, data storage and retrieval options, text editors, and reporting technology. These are the basic building blocks I recommend using just about any time you find yourself working with data. There are times however when more is needed. For example, you may wish to use distributed computing for large or resource intensive computations.

### Computing clusters at Harvard

Harvard provides a number of computing clusters, including Odyssey and the Research Computing Environment. Using these systems will be much easier if you know the basic tools well. After all, you're still going to need data storage/retrieval, you'll still need a text editor write code, and a programming language to write it in. My advice is to master these basics, and learn the rest as you need it.

## Wrap up

### Feedback

These workshops are a work in progress. Suggestions and feedback are welcome: use the Request help button at the top of the page.

