<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Python Introduction | Data Science Workshops</title>
  <meta name="description" content="Python Introduction | Data Science Workshops" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Python Introduction | Data Science Workshops" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Python Introduction | Data Science Workshops" />
  <meta name="github-repo" content="IQSS/dss-workshops" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Python Introduction | Data Science Workshops" />
  
  <meta name="twitter:description" content="Python Introduction | Data Science Workshops" />
  

<meta name="author" content="" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="PythonInstall.html"/>
<link rel="next" href="PythonWebScrape.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science Workshop Materials</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Table of Contents</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="part"><span><b>I General</b></span></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html"><i class="fa fa-check"></i>Data Science Tools</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#tools-for-working-with-data"><i class="fa fa-check"></i>Tools for working with data</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#the-puzzle-pieces"><i class="fa fa-check"></i>The puzzle pieces</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#data-analysis-building-blocks"><i class="fa fa-check"></i>Data analysis building blocks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#examples"><i class="fa fa-check"></i>Examples</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#old-school-example"><i class="fa fa-check"></i>Old-school example</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#something-old-something-new"><i class="fa fa-check"></i>Something old &amp; something new</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#a-modern-version"><i class="fa fa-check"></i>A modern version</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#data-storage-retrieval"><i class="fa fa-check"></i>Data storage &amp; retrieval</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#text-files"><i class="fa fa-check"></i>Text files</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#binary-files"><i class="fa fa-check"></i>Binary files</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#databases"><i class="fa fa-check"></i>Databases</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#distributed-file-storage"><i class="fa fa-check"></i>Distributed file storage</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#programming-languages-statistics-packages"><i class="fa fa-check"></i>Programming languages &amp; statistics packages</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#programming-language-features"><i class="fa fa-check"></i>Programming language features</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#program-comparison"><i class="fa fa-check"></i>Program comparison</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#examples-read-data-from-a-file-summarize"><i class="fa fa-check"></i>Examples: Read data from a file &amp; summarize</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#examples-fit-a-linear-regression"><i class="fa fa-check"></i>Examples: Fit a linear regression</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#examples-extract-links-for-.html-file"><i class="fa fa-check"></i>Examples: Extract links for .html file</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#creating-reports"><i class="fa fa-check"></i>Creating reports</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#markup-languages"><i class="fa fa-check"></i>Markup languages</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#word-processors"><i class="fa fa-check"></i>Word processors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#text-editors-integrated-development-environments"><i class="fa fa-check"></i>Text editors &amp; Integrated Development Environments</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#language-specific-editors-ides"><i class="fa fa-check"></i>Language specific editors &amp; IDEs</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#general-purpose-editors-ides"><i class="fa fa-check"></i>General purpose editors &amp; IDEs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#literate-programming-notebooks"><i class="fa fa-check"></i>Literate programming &amp; notebooks</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#literate-programming"><i class="fa fa-check"></i>Literate programming</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#notebooks"><i class="fa fa-check"></i>Notebooks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#big-data-annoying-data-computationally-intensive-methods"><i class="fa fa-check"></i>Big data, annoying data, &amp; computationally intensive methods</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#computing-clusters-at-harvard"><i class="fa fa-check"></i>Computing clusters at Harvard</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#wrap-up"><i class="fa fa-check"></i>Wrap up</a><ul>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#feedback"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="DataScienceTools.html"><a href="DataScienceTools.html#resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II R</b></span></li>
<li class="chapter" data-level="" data-path="Rinstall.html"><a href="Rinstall.html"><i class="fa fa-check"></i>R Installation</a><ul>
<li class="chapter" data-level="" data-path="Rinstall.html"><a href="Rinstall.html#troubleshooting-session"><i class="fa fa-check"></i>Troubleshooting session</a></li>
<li class="chapter" data-level="" data-path="Rinstall.html"><a href="Rinstall.html#materials"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="Rinstall.html"><a href="Rinstall.html#software"><i class="fa fa-check"></i>Software</a></li>
<li><a href="Rinstall.html#installing-the-tidyverse">Installing the <code>tidyverse</code></a><ul>
<li><a href="Rinstall.html#troubleshooting-tidyverse-installation">Troubleshooting <code>tidyverse</code> installation</a></li>
</ul></li>
<li><a href="Rinstall.html#installing-rmarkdown-optional">Installing <code>rmarkdown</code> (optional)</a></li>
<li class="chapter" data-level="" data-path="Rinstall.html"><a href="Rinstall.html#resources-1"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html"><i class="fa fa-check"></i>R Introduction</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#setup"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#software-and-materials"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#class-structure"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#goals"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#r-basics"><i class="fa fa-check"></i>R basics</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#what-is-r"><i class="fa fa-check"></i>What is R?</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#why-use-r"><i class="fa fa-check"></i>Why use R?</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#how-does-r-work"><i class="fa fa-check"></i>How does R work?</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#interfaces"><i class="fa fa-check"></i>Interfaces</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#launch-a-session"><i class="fa fa-check"></i>Launch a session</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-0"><i class="fa fa-check"></i>Exercise 0</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#syntax-rules"><i class="fa fa-check"></i>Syntax rules</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#function-calls"><i class="fa fa-check"></i>Function calls</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#assignment"><i class="fa fa-check"></i>Assignment</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#asking-for-help"><i class="fa fa-check"></i>Asking for help</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#reading-data"><i class="fa fa-check"></i>Reading data</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#installing-using-packages"><i class="fa fa-check"></i>Installing &amp; using packages</a></li>
<li><a href="Rintro.html#the-tidyverse">The <code>tidyverse</code></a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#readers-for-common-file-types"><i class="fa fa-check"></i>Readers for common file types</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#baby-names-data"><i class="fa fa-check"></i>Baby names data</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-1"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#manipulating-data"><i class="fa fa-check"></i>Manipulating data</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#filter-select-arrange"><i class="fa fa-check"></i>Filter, select, &amp; arrange</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#logical-relational-operators"><i class="fa fa-check"></i>Logical &amp; relational operators</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-2.1"><i class="fa fa-check"></i>Exercise 2.1</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#pipe-operator"><i class="fa fa-check"></i>Pipe operator</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-2.2"><i class="fa fa-check"></i>Exercise 2.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#plotting-data"><i class="fa fa-check"></i>Plotting data</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-3"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#creating-variables"><i class="fa fa-check"></i>Creating variables</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#create-or-modify-columns"><i class="fa fa-check"></i>Create or modify columns</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#operating-by-group"><i class="fa fa-check"></i>Operating by group</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#recoding-variables"><i class="fa fa-check"></i>Recoding variables</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-4"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#aggregating-variables"><i class="fa fa-check"></i>Aggregating variables</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#exercise-5"><i class="fa fa-check"></i>Exercise 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#saving-work"><i class="fa fa-check"></i>Saving work</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#saving-individual-datasets"><i class="fa fa-check"></i>Saving individual datasets</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#saving-multiple-datasets"><i class="fa fa-check"></i>Saving multiple datasets</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#saving-loading-workspaces"><i class="fa fa-check"></i>Saving &amp; loading workspaces</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#wrap-up-1"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#feedback-1"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="Rintro.html"><a href="Rintro.html#resources-2"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html"><i class="fa fa-check"></i>R Regression Models</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#setup-1"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#software-and-materials-1"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#class-structure-1"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#prerequisites-1"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#goals-1"><i class="fa fa-check"></i>Goals</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#launch-an-r-session"><i class="fa fa-check"></i>Launch an R session</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#packages"><i class="fa fa-check"></i>Packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#modeling-workflow"><i class="fa fa-check"></i>Modeling workflow</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#r-modeling-ecosystem"><i class="fa fa-check"></i>R modeling ecosystem</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#before-fitting-a-model"><i class="fa fa-check"></i>Before fitting a model</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#load-the-data"><i class="fa fa-check"></i>Load the data</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#examine-the-data"><i class="fa fa-check"></i>Examine the data</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#plot-the-data"><i class="fa fa-check"></i>Plot the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#models-with-continuous-outcomes"><i class="fa fa-check"></i>Models with continuous outcomes</a><ul>
<li><a href="Rmodels.html#why-is-the-association-between-expense-sat-scores-negative">Why is the association between expense &amp; SAT scores <em>negative</em>?</a></li>
<li><a href="Rmodels.html#the-lm-class-methods">The <code>lm</code> class &amp; methods</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#ols-regression-assumptions"><i class="fa fa-check"></i>OLS regression assumptions</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#comparing-models"><i class="fa fa-check"></i>Comparing models</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#exercise-0-1"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#interactions-factors"><i class="fa fa-check"></i>Interactions &amp; factors</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#modeling-interactions"><i class="fa fa-check"></i>Modeling interactions</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#regression-with-categorical-predictors"><i class="fa fa-check"></i>Regression with categorical predictors</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#setting-factor-reference-groups-contrasts"><i class="fa fa-check"></i>Setting factor reference groups &amp; contrasts</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#exercise-1-1"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#models-with-binary-outcomes"><i class="fa fa-check"></i>Models with binary outcomes</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#logistic-regression"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#logistic-regression-example"><i class="fa fa-check"></i>Logistic regression example</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#odds-ratios"><i class="fa fa-check"></i>Odds ratios</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#predicted-marginal-means"><i class="fa fa-check"></i>Predicted marginal means</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#exercise-2"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#multilevel-modeling"><i class="fa fa-check"></i>Multilevel modeling</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#multilevel-modeling-overview"><i class="fa fa-check"></i>Multilevel modeling overview</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#the-exam-data"><i class="fa fa-check"></i>The Exam data</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#the-null-model-icc"><i class="fa fa-check"></i>The null model &amp; ICC</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#adding-fixed-effects-predictors"><i class="fa fa-check"></i>Adding fixed-effects predictors</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#multiple-degree-of-freedom-comparisons"><i class="fa fa-check"></i>Multiple degree of freedom comparisons</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#random-slopes"><i class="fa fa-check"></i>Random slopes</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#test-the-significance-of-the-random-slope"><i class="fa fa-check"></i>Test the significance of the random slope</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#exercise-3-1"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#wrap-up-2"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#feedback-2"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="Rmodels.html"><a href="Rmodels.html#resources-3"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html"><i class="fa fa-check"></i>R Graphics</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#setup-2"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#software-and-materials-2"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#class-structure-2"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#prerequisites-2"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#launch-an-r-session-1"><i class="fa fa-check"></i>Launch an R session</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#packages-1"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#goals-2"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li><a href="Rgraphics.html#why-ggplot2">Why <code>ggplot2</code>?</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#what-is-the-grammar-of-graphics"><i class="fa fa-check"></i>What is the Grammar Of Graphics?</a></li>
<li><a href="Rgraphics.html#ggplot2-vs-base-graphics"><code>ggplot2</code> VS base graphics</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#geometric-objects-aesthetics"><i class="fa fa-check"></i>Geometric objects &amp; aesthetics</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#aesthetic-mapping"><i class="fa fa-check"></i>Aesthetic mapping</a></li>
<li><a href="Rgraphics.html#geometric-objects-geom">Geometric objects (<code>geom</code>)</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#aesthetic-mapping-vs-assignment"><i class="fa fa-check"></i>Aesthetic mapping VS assignment</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#mapping-variables-to-other-aesthetics"><i class="fa fa-check"></i>Mapping variables to other aesthetics</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#exercise-0-2"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#statistical-transformations"><i class="fa fa-check"></i>Statistical transformations</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#why-transform-data"><i class="fa fa-check"></i>Why transform data?</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#setting-arguments"><i class="fa fa-check"></i>Setting arguments</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#changing-the-transformation"><i class="fa fa-check"></i>Changing the transformation</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#exercise-1-2"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#scales"><i class="fa fa-check"></i>Scales</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#controlling-aesthetic-mapping"><i class="fa fa-check"></i>Controlling aesthetic mapping</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#common-scale-arguments"><i class="fa fa-check"></i>Common scale arguments</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#scale-modification-examples"><i class="fa fa-check"></i>Scale modification examples</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#using-different-color-scales"><i class="fa fa-check"></i>Using different color scales</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#available-scales"><i class="fa fa-check"></i>Available scales</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#exercise-2-1"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#faceting"><i class="fa fa-check"></i>Faceting</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#what-is-faceting"><i class="fa fa-check"></i>What is faceting?</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#what-is-the-trend-in-housing-prices-in-each-state"><i class="fa fa-check"></i>What is the trend in housing prices in each state?</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#faceting-to-the-rescue"><i class="fa fa-check"></i>Faceting to the rescue</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#themes"><i class="fa fa-check"></i>Themes</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#what-are-themes"><i class="fa fa-check"></i>What are themes?</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#overriding-theme-defaults"><i class="fa fa-check"></i>Overriding theme defaults</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#creating-saving-new-themes"><i class="fa fa-check"></i>Creating &amp; saving new themes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#saving-plots"><i class="fa fa-check"></i>Saving plots</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#the-1-faq"><i class="fa fa-check"></i>The #1 FAQ</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#map-aesthetic-to-different-columns"><i class="fa fa-check"></i>Map aesthetic to different columns</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#exercise-3-2"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#wrap-up-3"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#feedback-3"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="Rgraphics.html"><a href="Rgraphics.html#resources-4"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html"><i class="fa fa-check"></i>R Data Wrangling</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#setup-3"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#software-and-materials-3"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#class-structure-3"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#prerequisites-3"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#launch-an-r-session-2"><i class="fa fa-check"></i>Launch an R session</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#packages-2"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#workshop-outline"><i class="fa fa-check"></i>Workshop Outline</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#working-with-excel-worksheets"><i class="fa fa-check"></i>Working with Excel worksheets</a><ul>
<li><a href="RDataWrangling.html#iterating-with-map">Iterating with <code>map()</code></a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#filtering-strings-using-regex"><i class="fa fa-check"></i>Filtering strings using regex</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#writing-your-own-functions"><i class="fa fa-check"></i>Writing your own functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#reading-excel-data-files"><i class="fa fa-check"></i>Reading Excel data files</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#exercise-1-3"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#data-cleanup"><i class="fa fa-check"></i>Data cleanup</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#selecting-columns"><i class="fa fa-check"></i>Selecting columns</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#data-types-and-structures"><i class="fa fa-check"></i>Data types and structures</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#list-indexing"><i class="fa fa-check"></i>List indexing</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#dropping-missing-values"><i class="fa fa-check"></i>Dropping missing values</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#exercise-2-2"><i class="fa fa-check"></i>Exercise 2</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#reshaping-from-wide-to-long"><i class="fa fa-check"></i>Reshaping from wide to long</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#exercise-3-3"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#data-organization-storage"><i class="fa fa-check"></i>Data organization &amp; storage</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#a-list-of-data-frames"><i class="fa fa-check"></i>A list of data frames</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#one-big-data-frame"><i class="fa fa-check"></i>One big data frame</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#exercise-4-1"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#complete-code"><i class="fa fa-check"></i>Complete code</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#wrap-up-4"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#feedback-4"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="RDataWrangling.html"><a href="RDataWrangling.html#resources-5"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Python</b></span></li>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html"><i class="fa fa-check"></i>Python Installation</a><ul>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#troubleshooting-session-1"><i class="fa fa-check"></i>Troubleshooting session</a></li>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#materials-1"><i class="fa fa-check"></i>Materials</a></li>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#software-1"><i class="fa fa-check"></i>Software</a></li>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#jupyter-notebook-interfaces"><i class="fa fa-check"></i>Jupyter notebook interfaces</a><ul>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#launch-jupyterlab"><i class="fa fa-check"></i>Launch JupyterLab</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonInstall.html"><a href="PythonInstall.html#resources-6"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html"><i class="fa fa-check"></i>Python Introduction</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#setup-4"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#software-and-materials-4"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#class-structure-4"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#prerequisites-4"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#goals-3"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#python-basics"><i class="fa fa-check"></i>Python basics</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#what-is-python"><i class="fa fa-check"></i>What is Python?</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#why-use-python"><i class="fa fa-check"></i>Why use Python?</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#how-does-python-work"><i class="fa fa-check"></i>How does Python work?</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#interfaces-1"><i class="fa fa-check"></i>Interfaces</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#launch-jupyterlab-1"><i class="fa fa-check"></i>Launch JupyterLab</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#syntax-rules-1"><i class="fa fa-check"></i>Syntax rules</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#function-calls-1"><i class="fa fa-check"></i>Function calls</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#assignment-1"><i class="fa fa-check"></i>Assignment</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#reading-data-1"><i class="fa fa-check"></i>Reading data</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#object-methods"><i class="fa fa-check"></i>Object methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#using-object-methods-lists"><i class="fa fa-check"></i>Using object methods &amp; lists</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#splitting-a-string-into-a-list-of-words"><i class="fa fa-check"></i>Splitting a string into a list of words</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#working-with-lists"><i class="fa fa-check"></i>Working with lists</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#extracting-subsets-from-lists"><i class="fa fa-check"></i>Extracting subsets from lists</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#using-sets-to-count-unique-items"><i class="fa fa-check"></i>Using sets to count unique items</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#exercise-0-3"><i class="fa fa-check"></i>Exercise 0</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#control-flow"><i class="fa fa-check"></i>Control flow</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#logical-relational-operators-1"><i class="fa fa-check"></i>Logical &amp; relational operators</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#counting-list-elements"><i class="fa fa-check"></i>Counting list elements</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#exercise-1-4"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#iterating-over-collections-of-data"><i class="fa fa-check"></i>Iterating over collections of data</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#iterating-over-lists-using-for-loops"><i class="fa fa-check"></i>Iterating over lists using for-loops</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#organizing-results-in-dictionaries"><i class="fa fa-check"></i>Organizing results in dictionaries</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#exercise-2-3"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#importing-packages"><i class="fa fa-check"></i>Importing packages</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#wrap-up-5"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#feedback-5"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="PythonIntro.html"><a href="PythonIntro.html#resources-7"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html"><i class="fa fa-check"></i>Python Web-Scraping</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#setup-5"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#software-and-materials-5"><i class="fa fa-check"></i>Software and Materials</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#class-structure-5"><i class="fa fa-check"></i>Class Structure</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#prerequisites-5"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#goals-4"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#web-scraping-background"><i class="fa fa-check"></i>Web scraping background</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#what-is-web-scraping"><i class="fa fa-check"></i>What is web scraping?</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#is-web-scraping-legal-is-it-ethical"><i class="fa fa-check"></i>Is web scraping legal? Is it ethical?</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#web-scraping-approaches"><i class="fa fa-check"></i>Web scraping approaches</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#how-does-the-web-work"><i class="fa fa-check"></i>How does the web work?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#retrieve-data-in-json-format-if-you-can"><i class="fa fa-check"></i>Retrieve data in JSON format if you can</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#examine-the-websites-structure"><i class="fa fa-check"></i>Examine the website’s structure</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#launch-jupyterlab-2"><i class="fa fa-check"></i>Launch JupyterLab</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#making-requests"><i class="fa fa-check"></i>Making requests</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#parsing-json-data"><i class="fa fa-check"></i>Parsing JSON data</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#organizing-saving-the-data"><i class="fa fa-check"></i>Organizing &amp; saving the data</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#iterating-to-retrieve-all-the-data"><i class="fa fa-check"></i>Iterating to retrieve all the data</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#exercise-0-4"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#parsing-html-if-you-have-to"><i class="fa fa-check"></i>Parsing HTML if you have to</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#document-object-model-dom"><i class="fa fa-check"></i>Document Object Model (DOM)</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#retrieving-html"><i class="fa fa-check"></i>Retrieving HTML</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#parsing-html-using-the-lxml-library"><i class="fa fa-check"></i>Parsing HTML using the lxml library</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#using-xpath-to-extract-content-from-html"><i class="fa fa-check"></i>Using XPath to extract content from HTML</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#iterating-to-retrieve-content-from-a-list-of-html-elements"><i class="fa fa-check"></i>Iterating to retrieve content from a list of HTML elements</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#exercise-1-5"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li><a href="PythonWebScrape.html#scrapy-for-large-complex-projects"><code>Scrapy</code>: for large / complex projects</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#browser-drivers-a-last-resort"><i class="fa fa-check"></i>Browser drivers: a last resort</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#wrap-up-6"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#feedback-6"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="PythonWebScrape.html"><a href="PythonWebScrape.html#resources-8"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Stata</b></span></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html"><i class="fa fa-check"></i>Stata Introduction</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#setup-6"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#software-materials"><i class="fa fa-check"></i>Software &amp; Materials</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#organization"><i class="fa fa-check"></i>Organization</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#goals-5"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#why-stata"><i class="fa fa-check"></i>Why stata?</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#stata-interface"><i class="fa fa-check"></i>Stata interface</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#do-files"><i class="fa fa-check"></i>Do-files</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#stata-help"><i class="fa fa-check"></i>Stata help</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#syntax-rules-2"><i class="fa fa-check"></i>Syntax rules</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#lets-get-started"><i class="fa fa-check"></i>Let’s get started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#reading-data-2"><i class="fa fa-check"></i>Reading data</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#data-file-commands"><i class="fa fa-check"></i>Data file commands</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#a-note-about-path-names"><i class="fa fa-check"></i>A note about path names</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#wheres-my-data"><i class="fa fa-check"></i>Where’s my data?</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#reading-non-stata-data"><i class="fa fa-check"></i>Reading non-Stata data</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-0-5"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#statistics-graphs"><i class="fa fa-check"></i>Statistics &amp; graphs</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#frequently-used-commands"><i class="fa fa-check"></i>Frequently used commands</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#basic-graphing-commands"><i class="fa fa-check"></i>Basic graphing commands</a></li>
<li><a href="StataIntro.html#the-by-command">The <code>by</code> command</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-1-6"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#basic-data-management"><i class="fa fa-check"></i>Basic data management</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#labels"><i class="fa fa-check"></i>Labels</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#variable-value-labels"><i class="fa fa-check"></i>Variable &amp; value labels</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-2-4"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#working-on-subsets"><i class="fa fa-check"></i>Working on subsets</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#generating-replacing-variables"><i class="fa fa-check"></i>Generating &amp; replacing variables</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-3-4"><i class="fa fa-check"></i>Exercise 3</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#use-drop-to-delete-variables-and-keep-to-keep-them"><i class="fa fa-check"></i>Use drop to delete variables and keep to keep them</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#alternatively-you-can-keep-options-you-want"><i class="fa fa-check"></i>Alternatively, you can keep options you want</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-4-2"><i class="fa fa-check"></i>Exercise 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#exercise-solutions"><i class="fa fa-check"></i>Exercise solutions</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#ex-0-prototype"><i class="fa fa-check"></i>Ex 0: prototype</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#ex-1-prototype"><i class="fa fa-check"></i>Ex 1: prototype</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#ex-2-prototype"><i class="fa fa-check"></i>Ex 2: prototype</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#ex-3-prototype"><i class="fa fa-check"></i>Ex 3: prototype</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#ex-4-prototype"><i class="fa fa-check"></i>Ex 4: prototype</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#wrap-up-7"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#feedback-7"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="StataIntro.html"><a href="StataIntro.html#resources-9"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html"><i class="fa fa-check"></i>Stata Data Management</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#setup-7"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#software-materials-1"><i class="fa fa-check"></i>Software &amp; Materials</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#organization-1"><i class="fa fa-check"></i>Organization</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#goals-6"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#opening-files"><i class="fa fa-check"></i>Opening Files</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#generating-replacing-variables-1"><i class="fa fa-check"></i>Generating &amp; replacing variables</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#data-manipulation-commands"><i class="fa fa-check"></i>Data Manipulation Commands</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#generate-replace"><i class="fa fa-check"></i>Generate &amp; Replace</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#recode"><i class="fa fa-check"></i>Recode</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#egen"><i class="fa fa-check"></i>egen</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#exercise-0-6"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#by-processing"><i class="fa fa-check"></i>By processing</a><ul>
<li><a href="StataDatMan.html#the-bysort-command">The <code>bysort</code> Command</a></li>
<li><a href="StataDatMan.html#by-prefix-vs.-by-options"><code>by</code> prefix vs. <code>by</code> options</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#missing-values"><i class="fa fa-check"></i>Missing values</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#bulk-conversion-to-missing-values"><i class="fa fa-check"></i>Bulk Conversion to Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#variable-types"><i class="fa fa-check"></i>Variable types</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#converting-to-from-strings"><i class="fa fa-check"></i>Converting to &amp; from Strings</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#converting-strings-to-datetime"><i class="fa fa-check"></i>Converting Strings to Date/Time</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#formatting-numbers-as-dates"><i class="fa fa-check"></i>Formatting Numbers as Dates</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#exercise-1-7"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#merging-appending-joining"><i class="fa fa-check"></i>Merging, appending, &amp; joining</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#appending-datasets"><i class="fa fa-check"></i>Appending Datasets</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#merging-datasets"><i class="fa fa-check"></i>Merging Datasets</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#merge-options"><i class="fa fa-check"></i>Merge Options</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#many-to-many-merges"><i class="fa fa-check"></i>Many-to-many merges</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#creating-summarized-data-sets"><i class="fa fa-check"></i>Creating summarized data sets</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#collapse"><i class="fa fa-check"></i>Collapse</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#exercise-2-5"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#exercise-solutions-1"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#ex-0-prototype-1"><i class="fa fa-check"></i>Ex 0: prototype</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#ex-1-prototype-1"><i class="fa fa-check"></i>Ex 1: prototype</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#ex-2-prototype-1"><i class="fa fa-check"></i>Ex 2: prototype</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#wrap-up-8"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#feedback-8"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="StataDatMan.html"><a href="StataDatMan.html#resources-10"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html"><i class="fa fa-check"></i>Stata Modeling &amp; Graphing</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#setup-8"><i class="fa fa-check"></i>Setup</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#software-materials-2"><i class="fa fa-check"></i>Software &amp; Materials</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#organization-2"><i class="fa fa-check"></i>Organization</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#goals-7"><i class="fa fa-check"></i>Goals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#fitting-models"><i class="fa fa-check"></i>Fitting models</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#todays-dataset"><i class="fa fa-check"></i>Today’s Dataset</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#opening-files-1"><i class="fa fa-check"></i>Opening Files</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#simple-regression"><i class="fa fa-check"></i>Simple regression</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#steps-for-running-regression"><i class="fa fa-check"></i>Steps for running regression</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#sat-scores-education-expenditures"><i class="fa fa-check"></i>SAT scores &amp; Education Expenditures</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#ols-assumptions"><i class="fa fa-check"></i>OLS assumptions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#multiple-regression"><i class="fa fa-check"></i>Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#preliminaries-1"><i class="fa fa-check"></i>Preliminaries</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exercise-0-7"><i class="fa fa-check"></i>Exercise 0</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#interactions"><i class="fa fa-check"></i>Interactions</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#categorical-predictors"><i class="fa fa-check"></i>Categorical Predictors</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exercise-1-8"><i class="fa fa-check"></i>Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exporting-saving-results"><i class="fa fa-check"></i>Exporting &amp; saving results</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#regression-tables"><i class="fa fa-check"></i>Regression tables</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#saving-replaying"><i class="fa fa-check"></i>Saving &amp; replaying</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exporting-to-excel"><i class="fa fa-check"></i>Exporting to Excel</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#graphing-in-stata"><i class="fa fa-check"></i>Graphing in Stata</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#graphing-strategies"><i class="fa fa-check"></i>Graphing Strategies</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#terrible-graph"><i class="fa fa-check"></i>Terrible Graph</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#much-better-graph"><i class="fa fa-check"></i>Much Better Graph</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#univariate-graphics"><i class="fa fa-check"></i>Univariate Graphics</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#our-first-dataset"><i class="fa fa-check"></i>Our First Dataset</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#single-continuous-variables"><i class="fa fa-check"></i>Single Continuous Variables</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#single-categorical-variables"><i class="fa fa-check"></i>Single Categorical Variables</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exercise-2-6"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#bivariate-graphics"><i class="fa fa-check"></i>Bivariate Graphics</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#next-dataset"><i class="fa fa-check"></i>Next Dataset:</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#the-twoway-family"><i class="fa fa-check"></i>The Twoway Family</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#overlaying-twoway-graphs"><i class="fa fa-check"></i>Overlaying Twoway Graphs</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exercise-3-5"><i class="fa fa-check"></i>Exercise 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#twoway-line-graphs"><i class="fa fa-check"></i>Twoway Line Graphs</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exporting-graphs"><i class="fa fa-check"></i>Exporting Graphs</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#exercise-solutions-2"><i class="fa fa-check"></i>Exercise Solutions</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#ex-0-prototype-2"><i class="fa fa-check"></i>Ex 0: prototype</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#ex-1-prototype-2"><i class="fa fa-check"></i>Ex 1: prototype</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#ex-2-prototype-2"><i class="fa fa-check"></i>Ex 2: prototype</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#ex-3-prototype-1"><i class="fa fa-check"></i>Ex 3: prototype</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#wrap-up-9"><i class="fa fa-check"></i>Wrap-up</a><ul>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#feedback-9"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="StataModGraph.html"><a href="StataModGraph.html#resources-11"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science Workshops</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="python-introduction" class="section level1">
<h1>Python Introduction</h1>
<p><strong>Topics</strong></p>
<ul>
<li>Functions</li>
<li>Objects</li>
<li>Assignment</li>
<li>Finding help</li>
<li>List and dictionary structures</li>
<li>Indexing data structures</li>
<li>Iterating over collections of data</li>
<li>Importing packages</li>
</ul>
<div id="setup-4" class="section level2">
<h2>Setup</h2>
<div id="software-and-materials-4" class="section level3">
<h3>Software and Materials</h3>
<p>Follow the <a href="./PythonInstall.html">Python Installation</a> instructions and ensure that you can successfully start JupyterLab.</p>
<p>A handy <a href="Python/PythonIntro/python-cheat-sheet-basic.pdf">cheat-sheet</a> is available to help you look up and remember basic syntax.</p>
</div>
<div id="class-structure-4" class="section level3">
<h3>Class Structure</h3>
<p>Informal - Ask questions at any time. Really!</p>
<p>Collaboration is encouraged - please spend a minute introducing yourself to your neighbors!</p>
</div>
<div id="prerequisites-4" class="section level3">
<h3>Prerequisites</h3>
<p>This is an introductory Python course:</p>
<ul>
<li>Assumes no prior knowledge of <strong>how to use</strong> Python</li>
<li>We do assume you know <strong>why</strong> you want to learn Python. If you don’t, and want a comparison of Python to other statistical software, see our <a href="./DataScienceTools.html">Data Science Tools</a> workshop</li>
<li>Relatively slow-paced</li>
</ul>
</div>
<div id="goals-3" class="section level3">
<h3>Goals</h3>
<div class="alert alert-success">
<p>We will learn about the Python language by analyzing the text of Lewis Carroll’s <em>Alice’s Adventures in Wonderland</em>.
In particular, our goals are to learn about:</p>
<ol style="list-style-type: decimal">
<li>What Python is and how it works</li>
<li>How we can interact with Python</li>
<li>Foundations of the language (functions, objects, assignment, methods)</li>
<li>Using methods and lists to analyze data</li>
<li>Iterating over collections of data to automate repetitive tasks</li>
<li>Storing related data in dictionaries (as key - value pairs)</li>
<li>Importing packages to add functionality</li>
</ol>
</div>
</div>
</div>
<div id="python-basics" class="section level2">
<h2>Python basics</h2>
<div class="alert alert-info">
<p><strong>GOAL: To learn about the foundations of the Python language.</strong></p>
<ol style="list-style-type: decimal">
<li>What Python is and how it works</li>
<li>Python interfaces</li>
<li>Functions</li>
<li>Objects</li>
<li>Assignment</li>
<li>Methods</li>
</ol>
</div>
<div id="what-is-python" class="section level3">
<h3>What is Python?</h3>
<ul>
<li>Python is a free general purpose programming language</li>
<li>Python is an interpreted language, not a compiled one, meaning that all commands
typed on the keyboard are directly executed without requiring to build a complete
program (this is like R and unlike C, Fortran, Pascal, etc.)</li>
<li>Python has existed for about 30 years</li>
<li>Python is modular — most functionality is from add-on packages. So the language can
be thought of as a <em>platform</em> for creating and running a large number of useful packages.</li>
</ul>
</div>
<div id="why-use-python" class="section level3">
<h3>Why use Python?</h3>
<ul>
<li>Relatively easy to learn</li>
<li>Extremely flexible: can be used to manipulate, analyze, and visualize data,
make web sites, write games, and much more (Youtube and DropBox were written in Python)</li>
<li>Cutting edge machine learning tools</li>
<li>Publication quality graphics</li>
<li>150,000+ add on packages covering all aspects of statistics and machine learning</li>
<li>Active community of users</li>
</ul>
</div>
<div id="how-does-python-work" class="section level3">
<h3>How does Python work?</h3>
<p>While graphical-based statistical software (e.g., SPSS, GraphPad) immediately display
the results of an analysis, <strong>Python stores results in an <code>object</code> (a data structure)</strong>,
so that an analysis can be done with no result displayed. Such a feature is very
useful, since a user can extract only that part of the results that is of interest
and can pass results into further analyses.</p>
<p>For example, if you run a series of 20 regressions and want to compare the
different regression coefficients, Python can display only the estimated coefficients:
thus the results may take a single line, whereas graphical-based software could
open 20 results windows. In addition, these regression coefficients can be passed
directly into further analyses — such as generating predictions.</p>
<p><img src="Python/PythonIntro/images/python_chain.png" /></p>
<p>When Python is running, variables, data, functions, results, etc., are <strong>stored in memory</strong>
on the computer in the form of <code>objects</code> that have a name. The user can
<strong>perform actions</strong> on these objects with <code>operators</code> (arithmetic, logical,
comparison, etc.) and <code>functions</code> (which are themselves objects). Here’s a
schematic of how this all fits together:</p>
<p><img src="Python/PythonIntro/images/python_works.png" /></p>
</div>
<div id="interfaces-1" class="section level3">
<h3>Interfaces</h3>
<div id="text-editors-ides-notebooks-1" class="section level4">
<h4>Text editors, IDEs, &amp; Notebooks</h4>
<p>There are different ways of interacting with Python. The two main ways are through:</p>
<ol style="list-style-type: decimal">
<li><strong>text editors</strong> or <strong>Integrated Development Environments (IDEs):</strong> Text editors and IDEs are not really separate categories; as you add features to a text editor it becomes more like an IDE. Some editors/IDEs are language-specific while others are general purpose — typically providing language support via plugins. The following table lists a few popular editors/IDEs that can be used with Python. In this workshop, we will use <a href="https://jupyter.org/">JupyterLab</a>, a modern “extensible environment for interactive and reproducible computing” that runs in your web browser.</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="left">Editor / IDE</th>
<th align="left">Features</th>
<th align="left">Ease of use</th>
<th align="left">Language support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Spyder</td>
<td align="left">Excellent</td>
<td align="left">Easy</td>
<td align="left">Python only</td>
</tr>
<tr class="even">
<td align="left">PyCharm</td>
<td align="left">Excellent</td>
<td align="left">Moderate</td>
<td align="left">Python only</td>
</tr>
<tr class="odd">
<td align="left">JupyterLab</td>
<td align="left">Good</td>
<td align="left">Easy</td>
<td align="left">Excellent</td>
</tr>
<tr class="even">
<td align="left">VS code</td>
<td align="left">Excellent</td>
<td align="left">Easy</td>
<td align="left">Very good</td>
</tr>
<tr class="odd">
<td align="left">Atom</td>
<td align="left">Good</td>
<td align="left">Moderate</td>
<td align="left">Good</td>
</tr>
<tr class="even">
<td align="left">Vim</td>
<td align="left">Excellent</td>
<td align="left">Hard</td>
<td align="left">Good</td>
</tr>
<tr class="odd">
<td align="left">Emacs</td>
<td align="left">Excellent</td>
<td align="left">Hard</td>
<td align="left">Excellent</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li><strong>Notebooks:</strong> Browser-based applications that allow you to create and share documents that contain live code, equations, visualizations, and narrative text. One popular choice is <a href="https://jupyter.org/">Jupyter Notebook</a>; an open source notebook that has support for 40+ languages, but has limited features compared with the JupyterLab IDE.</li>
</ol>
</div>
<div id="source-code-literate-programming-1" class="section level4">
<h4>Source code &amp; literate programming</h4>
<p>There are also several different <strong>formats</strong> available for writing code in Python.
These basically boil down to a choice between:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Source code:</strong> the practice of writing code, and possibly comments, in a plain text document. In Python this is done by writing code in a text file with a <code>.py</code> extension. Writing source code has the great advantage of being simple. Souce code is the format of choice if you intend to run your code as a complete script - for example, from the command line.</p></li>
<li><p><strong>Literate programming:</strong> the practice of embedding computer code in a natural language document. In Python this is often done using the aformentioned <a href="https://jupyter.org/">Jupyter Notebook</a>, which is a <a href="https://www.json.org/json-en.html">JSON</a> document containing an ordered list of input/output cells which can contain code, text (using <em>Markdown</em>), mathematics, plots, and rich media, usually ending with the <code>.ipynb</code> extension. Jupyter Notebooks are easy to write, human-readable, and the format of choice if you intend to run your code interactively, by running small pieces of code and looking at each output. Researchers can use Notebooks to write their journal papers, dissertations, and statistics/math class notes, since it is easy to convert into other formats later, such as HTML (for a webpage), MS Word, or PDF (via LaTeX).</p></li>
</ol>
<p>Here are some resources for learning more about Jupyter Notebooks:</p>
<ul>
<li><a href="https://www.dataquest.io/blog/jupyter-notebook-tutorial/" class="uri">https://www.dataquest.io/blog/jupyter-notebook-tutorial/</a></li>
<li><a href="https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook" class="uri">https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook</a></li>
<li><a href="https://realpython.com/jupyter-notebook-introduction/" class="uri">https://realpython.com/jupyter-notebook-introduction/</a></li>
</ul>
</div>
</div>
<div id="launch-jupyterlab-1" class="section level3">
<h3>Launch JupyterLab</h3>
<ol style="list-style-type: decimal">
<li>Start the <code>Anaconda Navigator</code> program</li>
<li>Click the <code>Launch</code> button under <code>JupyterLab</code></li>
<li>A browser window will open with your computer’s files listed on the left hand side of the page. Navigate to the folder called <code>PythonIntro</code> that you downloaded to your desktop and double-click on the folder</li>
<li>Within the <code>PythonIntro</code> folder, double-click on the file with the word “BLANK” in the name (<code>PythonIntro_BLANK.ipynb</code>). A pop-up window will ask you to <code>Select Kernal</code> — you should select the Python 3 kernal. The Jupyter Notebook should now open on the right hand side of the page</li>
</ol>
<p>A Jupyter Notebook contains one or more <em>cells</em> containing notes or code. To insert a new cell click the <code>+</code> button in the upper left. To execute a cell, select it and press <code>Control+Enter</code> or click the <code>Run</code> button at the top.</p>
</div>
<div id="syntax-rules-1" class="section level3">
<h3>Syntax rules</h3>
<ul>
<li>Python is case sensitive</li>
<li>Python uses white space as part of the syntax (it’s important!)</li>
<li>Variable names should start with a letter (A-Z and a-z)
and can include letters, digits (0-9), and underscores (_)</li>
<li>Comments can be inserted using a hash <code>#</code> symbol</li>
<li>Functions must be written with parentheses, even
if there is nothing within them; for example: <code>len()</code></li>
</ul>
</div>
<div id="function-calls-1" class="section level3">
<h3>Function calls</h3>
<p><strong>Functions perform actions</strong> — they take some input, called <code>arguments</code> and return some
output (i.e., a result). Here’s a schematic of how a function works:</p>
<p><img src="Python/PythonIntro/images/function.png" /></p>
<p>The general form for calling Python functions is</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb480-1" data-line-number="1"><span class="co"># function_name(arg1, arg2, arg3, ... argn)</span></a></code></pre></div>
<p>The arguments in a function can be objects (data, formulae, expressions, etc.),
some of which could be defined by default in the function; these default values may
be modified by the user by specifying options.</p>
</div>
<div id="assignment-1" class="section level3">
<h3>Assignment</h3>
<p>In Python we can assign an object (data structure) to an name using the <code>=</code> operator.</p>
<div class="sourceCode" id="cb481"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb481-1" data-line-number="1"><span class="co"># name = thing_to_assign</span></a>
<a class="sourceLine" id="cb481-2" data-line-number="2">x <span class="op">=</span> <span class="dv">10</span></a></code></pre></div>
<p>The name on the left of the equals sign is one that we chose. When choosing names, they must:</p>
<ol style="list-style-type: decimal">
<li>start with a <em>letter</em></li>
<li>use only <em>letters</em>, <em>numbers</em> and <em>underscores</em></li>
</ol>
</div>
<div id="reading-data-1" class="section level3">
<h3>Reading data</h3>
<p>Reading information from a file is the first step in many projects, so we’ll use functions to read data into Python and assign them to a named object. The workshop materials you downloaded earlier include a file named <code>Alice_in_wonderland.txt</code> which contains the text of Lewis Carroll’s <em>Alice’s Adventures in Wonderland</em>. We can use the <code>open()</code> function to create a file <strong>object</strong> that makes a <strong>connection</strong> to the file:</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb482-1" data-line-number="1">alice_file <span class="op">=</span> <span class="bu">open</span>(<span class="st">&quot;Alice_in_wonderland.txt&quot;</span>)</a></code></pre></div>
<p>The <code>alice_file</code> object name we just created does <em>not</em> contain the contents of <code>Alice_in_wonderland.txt</code>. It is a representation in Python of the <em>file itself</em> rather than the <em>contents</em> of the file.</p>
</div>
<div id="object-methods" class="section level3">
<h3>Object methods</h3>
<p>The <code>alice_file</code> object provides <em>methods</em> that we can use to do things with it. Methods are invoked using syntax that looks like <code>ObjectName.method()</code>. You can see the methods available for acting on an object by typing the object’s name followed by a <code>.</code> and pressing the <code>tab</code> key. For example, typing <code>alice_file.</code> and pressing <code>tab</code> will display a list of methods as shown below.</p>
<p><img src="Python/PythonIntro/images/notebook_file_completion.png" />.</p>
<p>Among the methods we have for doing things with our <code>alice_file</code> object is one named <code>read</code>. We can use the <code>help</code> function to learn more about it.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb483-1" data-line-number="1"><span class="bu">help</span>(alice_file.read)</a></code></pre></div>
<pre><code>## Help on built-in function read:
## 
## read(size=-1, /) method of _io.TextIOWrapper instance
##     Read at most n characters from stream.
##     
##     Read from underlying buffer until we have n characters or we hit EOF.
##     If n is negative or omitted, read until EOF.</code></pre>
<p>Since <code>alice_file.read</code> looks promising, we will invoke this method and see what it does.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb485-1" data-line-number="1">alice_txt <span class="op">=</span> alice_file.read()</a>
<a class="sourceLine" id="cb485-2" data-line-number="2"><span class="bu">print</span>(alice_txt[:<span class="dv">500</span>]) <span class="co"># the [:500] gets the first 500 character -- more on this later.</span></a></code></pre></div>
<pre><code>## ﻿ALICE&#39;S ADVENTURES IN WONDERLAND
## 
## by
## 
## Lewis Carroll
## 
## CHAPTER I. Down the Rabbit-Hole
## 
## Alice was beginning to get very tired of sitting by her sister on the
## bank, and of having nothing to do: once or twice she had peeped into the
## book her sister was reading, but it had no pictures or conversations in
## it, &#39;and what is the use of a book,&#39; thought Alice &#39;without pictures or
## conversations?&#39;
## 
## So she was considering in her own mind (as well as she could, for the
## hot day made her feel very sleepy and s</code></pre>
<p>That’s all there is to it! We’ve read the contents of <code>Alice_in_wonderland.txt</code> and stored this text in a Python object we named <code>alice_txt</code>. Now let’s start to explore this object, and learn some more things about Python along the way.</p>
</div>
</div>
<div id="using-object-methods-lists" class="section level2">
<h2>Using object methods &amp; lists</h2>
<div class="alert alert-info">
<p><strong>GOAL: To learn how to use methods and lists to analyze data.</strong> We will do this using the Alice text to count:</p>
<ol style="list-style-type: decimal">
<li>Words</li>
<li>Chapters</li>
<li>Paragraphs</li>
</ol>
</div>
<p>How many words does the text contain? To answer this question, we can split the text up so there is one element per word, and then count the number of words.</p>
<div id="splitting-a-string-into-a-list-of-words" class="section level3">
<h3>Splitting a string into a list of words</h3>
<p>How do we figure out how to split strings in Python? We can ask Python what our <code>alice_txt</code> object is and what methods it provides. We can ask Python what things are using the <code>type()</code> function, like this:</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb487-1" data-line-number="1"><span class="bu">type</span>(alice_txt)</a></code></pre></div>
<pre><code>## &lt;class &#39;str&#39;&gt;</code></pre>
<p>Python tells us that <code>alice_txt</code> is of type <code>str</code> (i.e., it is a string). We can find out what methods are available for working strings by typing <code>alice_txt.</code> and pressing <code>tab</code>. We’ll see that among the methods is one named <code>split</code>, as shown below.</p>
<p><img src="Python/PythonIntro/images/notebook_string_completion.png" /></p>
<p>To learn how to use this method we can check the documentation.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb489-1" data-line-number="1"><span class="bu">help</span>(alice_txt.split)</a></code></pre></div>
<pre><code>## Help on built-in function split:
## 
## split(sep=None, maxsplit=-1) method of builtins.str instance
##     Return a list of the words in the string, using sep as the delimiter string.
##     
##     sep
##       The delimiter according which to split the string.
##       None (the default value) means split according to any whitespace,
##       and discard empty strings from the result.
##     maxsplit
##       Maximum number of splits to do.
##       -1 (the default value) means no limit.</code></pre>
<p>Since the default is to split on whitespace (spaces, newlines, tabs) we can get a reasonable word count simply by calling the split method and counting the number of elements in the result.</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb491-1" data-line-number="1">alice_words <span class="op">=</span> alice_txt.split() <span class="co"># returns a list</span></a>
<a class="sourceLine" id="cb491-2" data-line-number="2"><span class="bu">type</span>(alice_words)</a></code></pre></div>
<pre><code>## &lt;class &#39;list&#39;&gt;</code></pre>
</div>
<div id="working-with-lists" class="section level3">
<h3>Working with lists</h3>
<p>The <code>split</code> methods we used to break up the text of <em>Alice in Wonderland</em> into words produced a <em>list</em>. A lot of the techniques we’ll use later to analyze this text also produce lists, so its worth taking a few minutes to learn more about them.</p>
<p>Note that the displayed representation of lists and other data structures in Python often closely matches the syntax used to create them. For example, we can create a list using square brackets, just as we see when we print a list.</p>
<p>A <em>list</em> in Python is used to store a collection of items:</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb493-1" data-line-number="1"><span class="co"># create a list</span></a>
<a class="sourceLine" id="cb493-2" data-line-number="2">y <span class="op">=</span> [<span class="dv">1</span>, <span class="st">&quot;b&quot;</span>, <span class="dv">3</span>, <span class="st">&quot;D&quot;</span>, <span class="dv">5</span>, <span class="dv">6</span>]</a></code></pre></div>
<p>As with other types in Python, you can get a list of methods by typing the name of the object followed by a <code>.</code> and pressing <code>tab</code>.</p>
</div>
<div id="extracting-subsets-from-lists" class="section level3">
<h3>Extracting subsets from lists</h3>
<p>Among the things you can do with a list is extract subsets of items using <strong>bracket indexing notation</strong>. This is useful in many situations, including the current one where we want to inspect a long list without printing out the whole thing.</p>
<p>The examples below show how indexing works in Python. First using pseudocode:</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb494-1" data-line-number="1"><span class="co"># syntax</span></a>
<a class="sourceLine" id="cb494-2" data-line-number="2"><span class="co"># object[ start : end : by ]</span></a>
<a class="sourceLine" id="cb494-3" data-line-number="3"></a>
<a class="sourceLine" id="cb494-4" data-line-number="4"><span class="co"># defaults</span></a>
<a class="sourceLine" id="cb494-5" data-line-number="5"><span class="co"># object[ 0 : end : 1 ]</span></a></code></pre></div>
<p>Then using a real list:</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb495-1" data-line-number="1"><span class="co"># create a list</span></a>
<a class="sourceLine" id="cb495-2" data-line-number="2">y <span class="op">=</span> [<span class="dv">1</span>, <span class="st">&quot;b&quot;</span>, <span class="dv">3</span>, <span class="st">&quot;D&quot;</span>, <span class="dv">5</span>, <span class="dv">6</span>]</a>
<a class="sourceLine" id="cb495-3" data-line-number="3"></a>
<a class="sourceLine" id="cb495-4" data-line-number="4">y[<span class="dv">0</span>] <span class="co"># returns first element - the number 1 (yes, the index counts from zero!)</span></a></code></pre></div>
<pre><code>## 1</code></pre>
<div class="sourceCode" id="cb497"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb497-1" data-line-number="1">y[<span class="dv">1</span>] <span class="co"># returns second element - the letter &quot;b&quot;</span></a></code></pre></div>
<pre><code>## &#39;b&#39;</code></pre>
<div class="sourceCode" id="cb499"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb499-1" data-line-number="1">y[ :<span class="dv">3</span>] <span class="co"># returns a list with only the first 3 elements, but index is of length 4 (0 to 3) because last index is excluded</span></a></code></pre></div>
<pre><code>## [1, &#39;b&#39;, 3]</code></pre>
<div class="sourceCode" id="cb501"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb501-1" data-line-number="1">y[<span class="dv">2</span>:<span class="dv">5</span>] <span class="co"># returns a list with elements 3, &quot;D&quot;, 5</span></a></code></pre></div>
<pre><code>## [3, &#39;D&#39;, 5]</code></pre>
<div class="sourceCode" id="cb503"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb503-1" data-line-number="1">y[<span class="op">-</span><span class="dv">1</span>] <span class="co"># returns last element - the number 6 </span></a></code></pre></div>
<pre><code>## 6</code></pre>
<div class="sourceCode" id="cb505"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb505-1" data-line-number="1">y[<span class="op">-</span><span class="dv">4</span>: ] <span class="co"># returns a list with last 4 elements</span></a></code></pre></div>
<pre><code>## [3, &#39;D&#39;, 5, 6]</code></pre>
<div class="sourceCode" id="cb507"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb507-1" data-line-number="1">alice_words[<span class="dv">11</span>:<span class="dv">20</span>] <span class="co"># returns a list with words 11 through 19</span></a></code></pre></div>
<pre><code>## [&#39;Rabbit-Hole&#39;, &#39;Alice&#39;, &#39;was&#39;, &#39;beginning&#39;, &#39;to&#39;, &#39;get&#39;, &#39;very&#39;, &#39;tired&#39;, &#39;of&#39;]</code></pre>
<div class="sourceCode" id="cb509"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb509-1" data-line-number="1">alice_words[<span class="op">-</span><span class="dv">10</span>: ] <span class="co"># returns a list with the last 10 words</span></a></code></pre></div>
<pre><code>## [&#39;her&#39;, &#39;own&#39;, &#39;child-life,&#39;, &#39;and&#39;, &#39;the&#39;, &#39;happy&#39;, &#39;summer&#39;, &#39;days.&#39;, &#39;THE&#39;, &#39;END&#39;]</code></pre>
</div>
<div id="using-sets-to-count-unique-items" class="section level3">
<h3>Using sets to count unique items</h3>
<p>Now that we have a list containing the individual words from <em>Alice’s Adventures in Wonderland</em>, we can calculate how many words there are in total using the <code>len()</code> (length) function:</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb511-1" data-line-number="1"><span class="bu">len</span>(alice_words) <span class="co"># counts elements in a data structure</span></a></code></pre></div>
<pre><code>## 26445</code></pre>
<p>According to our above computation, there are about 26 thousand total words in the Alice text. But how many <em>unique</em> words are there? Python has a special data structure called a <em>set</em> that makes it easy to find out. A <em>set</em> drops all duplicates, giving a collection of the unique elements. Here’s a simple example:</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb513-1" data-line-number="1"><span class="co"># set example</span></a>
<a class="sourceLine" id="cb513-2" data-line-number="2">mylist <span class="op">=</span> {<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">4</span>, <span class="dv">5</span>}</a>
<a class="sourceLine" id="cb513-3" data-line-number="3"><span class="bu">set</span>(mylist)</a></code></pre></div>
<pre><code>## {1, 4, 5, 9}</code></pre>
<p>Now we can count the number of unique elements in the list by getting the length <code>len()</code> of the set <code>set()</code>:</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb515-1" data-line-number="1"><span class="bu">len</span>(<span class="bu">set</span>(mylist))</a></code></pre></div>
<pre><code>## 4</code></pre>
<p>We can now use the <code>set()</code> function to convert the list of all words (<code>alice_words</code>) into a set of <em>unique</em> words and then count them:</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb517-1" data-line-number="1"><span class="bu">len</span>(<span class="bu">set</span>(alice_words)) <span class="co"># counts unique elements in a data structure</span></a></code></pre></div>
<pre><code>## 5295</code></pre>
<p>There are 5295 unique words in the text.</p>
</div>
<div id="exercise-0-3" class="section level3">
<h3>Exercise 0</h3>
<p><strong>Reading text from a file &amp; splitting</strong></p>
<p><em>Alice’s Adventures in Wonderland</em> is full of memorable characters. The main characters from the story are listed, one-per-line, in the file named <code>Characters.txt</code>.</p>
<p>NOTE: we will not always explicitly demonstrate everything you need to know in order to complete an exercise. Instead we focus on teaching you how to discover available methods and how use the help function to learn how to use them. It is expected that you will spend some time during the exercises looking for appropriate methods and perhaps reading documentation.</p>
<ol style="list-style-type: decimal">
<li>Open the <code>Characters.txt</code> file and read its contents.</li>
</ol>
<div class="sourceCode" id="cb519"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb519-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Split text on newlines to produce a list with one element per line. Store the result as <code>alice_characters</code>. HINT: you can split on newlines using the <code>\n</code> separator.</li>
</ol>
<div class="sourceCode" id="cb520"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb520-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<details>
<summary><span style="color:red"><b>Click for Exercise 0 Solution</b></span></summary>
<div class="alert alert-danger">
<ol style="list-style-type: decimal">
<li>Open the Characters.txt file and read its contents.</li>
</ol>
<div class="sourceCode" id="cb521"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb521-1" data-line-number="1">characters_file <span class="op">=</span> <span class="bu">open</span>(<span class="st">&quot;Characters.txt&quot;</span>)</a>
<a class="sourceLine" id="cb521-2" data-line-number="2">characters_txt <span class="op">=</span> characters_file.read()</a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Split text on newlines to produce a list with one element per line.
Store the result as “alice_characters”.</li>
</ol>
<div class="sourceCode" id="cb522"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb522-1" data-line-number="1">alice_characters <span class="op">=</span> characters_txt.split(sep<span class="op">=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</a>
<a class="sourceLine" id="cb522-2" data-line-number="2">alice_characters</a></code></pre></div>
<pre><code>## [&#39;Alice&#39;, &#39;White Rabbit&#39;, &#39;Mouse&#39;, &#39;Dodo&#39;, &#39;Lory&#39;, &#39;Eaglet&#39;, &#39;Duck&#39;, &#39;Pat&#39;, &#39;Bill the Lizard&#39;, &#39;Puppy&#39;, &#39;Caterpillar&#39;, &#39;Duchess&#39;, &#39;Cheshire Cat&#39;, &#39;March Hare&#39;, &#39;Hatter&#39;, &#39;Dormouse&#39;, &#39;Queen of Hearts&#39;, &#39;Knave of Hearts&#39;, &#39;King of Hearts&#39;, &#39;Gryphon&#39;, &#39;Mock Turtle&#39;, &#39;&#39;]</code></pre>
</div>
</details>
</div>
<div id="control-flow" class="section level3">
<h3>Control flow</h3>
<p>Sometimes we may want to control the flow of code in an analysis using <strong>choices</strong>,
such as <code>if</code> and <code>else</code> statements, which allow you to run different code depending on the input.
The basic form is:</p>
<pre><code>```python
if (condition) true_action else false_action
```

If `condition` is `TRUE`, `true_action` is evaluated; if `condition` is `FALSE`,
the optional `false_action` is evaluated.</code></pre>
<p>The conditions that are evaluated use <strong>logical and relational operators</strong> to determine equivalence or make some other relational comparisons.</p>
</div>
<div id="logical-relational-operators-1" class="section level3">
<h3>Logical &amp; relational operators</h3>
<p>Here’s a table of commonly used relational operators:</p>
<table>
<thead>
<tr class="header">
<th align="left">Operator</th>
<th align="left">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>==</code></td>
<td align="left">equal to</td>
</tr>
<tr class="even">
<td align="left"><code>!=</code></td>
<td align="left">not equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>&gt;</code></td>
<td align="left">greater than</td>
</tr>
<tr class="even">
<td align="left"><code>&gt;=</code></td>
<td align="left">greater than or equal to</td>
</tr>
<tr class="odd">
<td align="left"><code>&lt;</code></td>
<td align="left">less than</td>
</tr>
<tr class="even">
<td align="left"><code>&lt;=</code></td>
<td align="left">less than or equal to</td>
</tr>
</tbody>
</table>
<p>These relational operators may be combined with logical operators, such as <code>and</code> or <code>or</code>, as we’ll see below.</p>
</div>
<div id="counting-list-elements" class="section level3">
<h3>Counting list elements</h3>
<p>Now that we know how to split a string and how to work with the resulting list, we can split on chapter markers to count the number of chapters. All we need to do is specify the string to split on. Since each chapter is marked with the string <code>'CHAPTER '</code> followed by the chapter number, we can split the text up into chapters using this as the separator.</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb525-1" data-line-number="1">alice_chapters <span class="op">=</span> alice_txt.split(<span class="st">&quot;CHAPTER &quot;</span>)</a>
<a class="sourceLine" id="cb525-2" data-line-number="2"><span class="bu">len</span>(alice_chapters)</a></code></pre></div>
<pre><code>## 13</code></pre>
<p>Since the first element contains the material <em>before</em> the first chapter, this tells us there are twelve chapters in the book.</p>
<p>We can also count the number of times the “Bunny” and “Duck” characters appear in a given Chapter, say Chapter 2:</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb527-1" data-line-number="1">bunny_count_ch2 <span class="op">=</span> alice_chapters[<span class="dv">2</span>].count(<span class="st">&quot;Bunny&quot;</span>)</a>
<a class="sourceLine" id="cb527-2" data-line-number="2"><span class="bu">print</span>(bunny_count_ch2)</a></code></pre></div>
<pre><code>## 0</code></pre>
<div class="sourceCode" id="cb529"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb529-1" data-line-number="1">duck_count_ch2 <span class="op">=</span> alice_chapters[<span class="dv">2</span>].count(<span class="st">&quot;Duck&quot;</span>)</a>
<a class="sourceLine" id="cb529-2" data-line-number="2"><span class="bu">print</span>(duck_count_ch2)</a></code></pre></div>
<pre><code>## 1</code></pre>
<p>By combining choice statements with logical and/or relational operators, we can then determine which of these two characters
appears more often in Chapter 2:</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb531-1" data-line-number="1"><span class="cf">if</span> bunny_count_ch2 <span class="op">&lt;</span> duck_count_ch2:</a>
<a class="sourceLine" id="cb531-2" data-line-number="2">    <span class="bu">print</span>(<span class="st">&quot;Bunny count is less than Duck count in Chapter II.&quot;</span>)</a>
<a class="sourceLine" id="cb531-3" data-line-number="3"><span class="cf">elif</span> bunny_count_ch2 <span class="op">&gt;</span> duck_count_ch2:</a>
<a class="sourceLine" id="cb531-4" data-line-number="4">    <span class="bu">print</span>(<span class="st">&quot;Bunny count is larger than Duck count in Chapter II.&quot;</span>)</a>
<a class="sourceLine" id="cb531-5" data-line-number="5"><span class="cf">else</span>:</a>
<a class="sourceLine" id="cb531-6" data-line-number="6">    <span class="bu">print</span>(<span class="st">&quot;Bunny count is equal to Duck count in Chapter II.&quot;</span>)</a></code></pre></div>
<pre><code>## Bunny count is less than Duck count in Chapter II.</code></pre>
<p>We can count paragraphs in a similar way to chapters. Paragraphs are indicated by a blank line, i.e., two newlines in a row. When working with strings we can represent newlines with <code>\n</code>. Paragraphs are indicated by two new lines, and so our basic paragraph separator is <code>\n\n</code>. We can see this separator by looking at the content.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb533-1" data-line-number="1"><span class="bu">print</span>(alice_txt[:<span class="dv">500</span>]) <span class="co"># explicit printing --- formats text nicely</span></a></code></pre></div>
<pre><code>## ﻿ALICE&#39;S ADVENTURES IN WONDERLAND
## 
## by
## 
## Lewis Carroll
## 
## CHAPTER I. Down the Rabbit-Hole
## 
## Alice was beginning to get very tired of sitting by her sister on the
## bank, and of having nothing to do: once or twice she had peeped into the
## book her sister was reading, but it had no pictures or conversations in
## it, &#39;and what is the use of a book,&#39; thought Alice &#39;without pictures or
## conversations?&#39;
## 
## So she was considering in her own mind (as well as she could, for the
## hot day made her feel very sleepy and s</code></pre>
<div class="sourceCode" id="cb535"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb535-1" data-line-number="1">alice_txt[:<span class="dv">500</span>] <span class="co"># returns content without printing it</span></a></code></pre></div>
<pre><code>## &quot;\ufeffALICE&#39;S ADVENTURES IN WONDERLAND\n\nby\n\nLewis Carroll\n\nCHAPTER I. Down the Rabbit-Hole\n\nAlice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, &#39;and what is the use of a book,&#39; thought Alice &#39;without pictures or\nconversations?&#39;\n\nSo she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and s&quot;</code></pre>
<div class="sourceCode" id="cb537"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb537-1" data-line-number="1">alice_paragraphs <span class="op">=</span> alice_txt.split(<span class="st">&quot;</span><span class="ch">\n\n</span><span class="st">&quot;</span>)</a></code></pre></div>
<p>Before counting the number of paragraphs, I want to inspect the result to see if it looks correct:</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb538-1" data-line-number="1"><span class="bu">print</span>(alice_paragraphs[<span class="dv">0</span>], <span class="st">&quot;</span><span class="ch">\n</span><span class="st">==========&quot;</span>)</a></code></pre></div>
<pre><code>## ﻿ALICE&#39;S ADVENTURES IN WONDERLAND 
## ==========</code></pre>
<div class="sourceCode" id="cb540"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb540-1" data-line-number="1"><span class="bu">print</span>(alice_paragraphs[<span class="dv">1</span>], <span class="st">&quot;</span><span class="ch">\n</span><span class="st">==========&quot;</span>)</a></code></pre></div>
<pre><code>## by 
## ==========</code></pre>
<div class="sourceCode" id="cb542"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb542-1" data-line-number="1"><span class="bu">print</span>(alice_paragraphs[<span class="dv">2</span>], <span class="st">&quot;</span><span class="ch">\n</span><span class="st">==========&quot;</span>)</a></code></pre></div>
<pre><code>## Lewis Carroll 
## ==========</code></pre>
<p>We’re counting the title, author, and chapter lines as paragraphs, but this will do for a rough count.</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb544-1" data-line-number="1"><span class="bu">len</span>(alice_paragraphs)</a></code></pre></div>
<pre><code>## 830</code></pre>
<p>Now let’s use a logical operator to find out if “Alice” or “Eaglet” appear in paragraph 11:</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb546-1" data-line-number="1">alice_eaglet_exist <span class="op">=</span> <span class="st">&quot;Alice&quot;</span> <span class="kw">in</span> alice_paragraphs[<span class="dv">10</span>] <span class="kw">or</span> <span class="st">&quot;Eaglet&quot;</span> <span class="kw">in</span> alice_paragraphs[<span class="dv">10</span>]</a>
<a class="sourceLine" id="cb546-2" data-line-number="2">alice_eaglet_exist</a></code></pre></div>
<pre><code>## True</code></pre>
</div>
<div id="exercise-1-4" class="section level3">
<h3>Exercise 1</h3>
<p><strong>Count the number of main characters</strong></p>
<p>So far we’ve learned that there are 12 chapters, around 830 paragraphs, and about 26 thousand words in <em>Alice’s Adventures in Wonderland</em>. Along the way we’ve also learned how to open a file and read its contents, split strings, calculate the length of objects, discover methods for string and list objects, and index/subset lists in Python. Now it is time for you to put these skills to use to learn something about the main characters in the story.</p>
<ol style="list-style-type: decimal">
<li>Count the number of main characters in the story (i.e., get the length of the list you created in previous exercise).</li>
</ol>
<div class="sourceCode" id="cb548"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb548-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Extract and print just the first character from the list you created in the previous exercise.</li>
</ol>
<div class="sourceCode" id="cb549"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb549-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Test whether the length of the 3rd and 8th character’s names are equal. Test whether the length of
the 3rd character’s name is greater than or equal to the length of the 6th character’s name. Now test
whether EITHER of the above conditions are true. HINT: use the <code>len()</code> function.</li>
</ol>
<div class="sourceCode" id="cb550"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb550-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>(BONUS, optional): Sort the list you created in step 2 alphabetically,
and then extract the last element.</li>
</ol>
<div class="sourceCode" id="cb551"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb551-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<details>
<summary><span style="color:red"><b>Click for Exercise 1 Solution</b></span></summary>
<div class="alert alert-danger">
<ol style="list-style-type: decimal">
<li>Count the number of main characters in the story (i.e., get the length of the list you created in previous exercise).</li>
</ol>
<div class="sourceCode" id="cb552"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb552-1" data-line-number="1"><span class="bu">len</span>(alice_characters)</a></code></pre></div>
<pre><code>## 22</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Extract and print just the first character from the list you created in the previous exercise.</li>
</ol>
<div class="sourceCode" id="cb554"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb554-1" data-line-number="1"><span class="bu">print</span>(alice_characters[<span class="dv">0</span>])</a></code></pre></div>
<pre><code>## Alice</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Test whether the length of the 3rd and 8th character’s names are equal. Test whether the length of
the 3rd character’s name is greater than or equal to the length of the 6th character’s name. Now test
whether EITHER of the above conditions are true. HINT: use the <code>len()</code> function.</li>
</ol>
<div class="sourceCode" id="cb556"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb556-1" data-line-number="1"><span class="bu">len</span>(alice_characters[<span class="dv">2</span>]) <span class="op">==</span> <span class="bu">len</span>(alice_characters[<span class="dv">7</span>]) <span class="kw">or</span> <span class="bu">len</span>(alice_characters[<span class="dv">2</span>]) <span class="op">&gt;=</span> <span class="bu">len</span>(alice_characters[<span class="dv">5</span>])</a></code></pre></div>
<pre><code>## False</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>(BONUS, optional): Sort the list you created in step 2 alphabetically,
and then extract the last element.</li>
</ol>
<div class="sourceCode" id="cb558"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb558-1" data-line-number="1">alice_characters.sort()</a>
<a class="sourceLine" id="cb558-2" data-line-number="2">alice_characters[<span class="op">-</span><span class="dv">1</span>]</a></code></pre></div>
<pre><code>## &#39;White Rabbit&#39;</code></pre>
</div>
</details>
</div>
</div>
<div id="iterating-over-collections-of-data" class="section level2">
<h2>Iterating over collections of data</h2>
<div class="alert alert-info">
<p><strong>GOAL: To learn how to automate repetitive tasks by iterating over collections of data.</strong> We will do this using the Alice text to count:</p>
<ol style="list-style-type: decimal">
<li>Words nested within paragraphs</li>
<li>Paragraphs nested within chapters</li>
</ol>
</div>
<p>This far our analysis has treated the text as a “flat” data structure. For example, when we counted words we just counted words in the whole document, rather than counting the number of words in each chapter. If we want to treat our document as a nested structure, with words forming sentences, sentences forming paragraphs, paragraphs forming chapters, and chapters forming the book, we need to learn some additional tools. Specifically, we need to learn how to iterate over lists (or other collections) and do things with each element in a collection.</p>
<p>There are several ways to iterate in Python, of which we will focus on <em>for loops</em>.</p>
<div id="iterating-over-lists-using-for-loops" class="section level3">
<h3>Iterating over lists using for-loops</h3>
<p>A <em>for loop</em> is a way of cycling through the elements of a collection and doing something with each one. The for loop logic is:</p>
<center>
<img src="Python/PythonIntro/images/for_loop_pic_small.png" />
</center>
<p>The for loop syntax is:</p>
<div class="sourceCode" id="cb560"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb560-1" data-line-number="1"><span class="cf">for</span> <span class="op">&lt;</span>thing<span class="op">&gt;</span> <span class="kw">in</span> <span class="op">&lt;</span>collection<span class="op">&gt;</span>:</a>
<a class="sourceLine" id="cb560-2" data-line-number="2">    do stuff <span class="cf">with</span> <span class="op">&lt;</span>thing<span class="op">&gt;</span></a></code></pre></div>
<center>
<img src="Python/PythonIntro/images/python_for_loop_small.png" />
</center>
<p>Notice that:</p>
<ol style="list-style-type: decimal">
<li><strong>the body of the for-loop is indented</strong>. This is important, because it is this indentation that defines the <em>body</em> of the loop — the place where things are done.</li>
<li><strong>White space matters in Python!</strong></li>
</ol>
<p>A simple example:</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb561-1" data-line-number="1"><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</a>
<a class="sourceLine" id="cb561-2" data-line-number="2">    <span class="bu">print</span>(i)</a></code></pre></div>
<pre><code>## 0
## 1
## 2
## 3
## 4
## 5
## 6
## 7
## 8
## 9</code></pre>
<div class="sourceCode" id="cb563"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb563-1" data-line-number="1"><span class="bu">print</span>(<span class="st">&#39;DONE.&#39;</span>)</a></code></pre></div>
<pre><code>## DONE.</code></pre>
<p>Notice that “DONE.” is only printed once, since <code>print('DONE.')</code> is not indented and is therefore outside of the body of the loop.</p>
<p>As a simple example using the Alice text, we can cycle through the first 6 paragraphs and print each one. Cycling through with a loop makes it easy to insert a separator between the paragraphs, making it much clearer to read the output:</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb565-1" data-line-number="1"><span class="cf">for</span> paragraph <span class="kw">in</span> alice_paragraphs[:<span class="dv">6</span>]:</a>
<a class="sourceLine" id="cb565-2" data-line-number="2">    <span class="bu">print</span>(paragraph)</a>
<a class="sourceLine" id="cb565-3" data-line-number="3">    <span class="bu">print</span>(<span class="st">&#39;==================================&#39;</span>)</a></code></pre></div>
<pre><code>## ﻿ALICE&#39;S ADVENTURES IN WONDERLAND
## ==================================
## by
## ==================================
## Lewis Carroll
## ==================================
## CHAPTER I. Down the Rabbit-Hole
## ==================================
## Alice was beginning to get very tired of sitting by her sister on the
## bank, and of having nothing to do: once or twice she had peeped into the
## book her sister was reading, but it had no pictures or conversations in
## it, &#39;and what is the use of a book,&#39; thought Alice &#39;without pictures or
## conversations?&#39;
## ==================================
## So she was considering in her own mind (as well as she could, for the
## hot day made her feel very sleepy and stupid), whether the pleasure
## of making a daisy-chain would be worth the trouble of getting up and
## picking the daisies, when suddenly a White Rabbit with pink eyes ran
## close by her.
## ==================================</code></pre>
<div class="sourceCode" id="cb567"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb567-1" data-line-number="1"><span class="bu">print</span>(<span class="st">&#39;DONE.&#39;</span>)</a></code></pre></div>
<pre><code>## DONE.</code></pre>
<p>Loops in Python are great because the syntax is relatively simple, and because they are very powerful. Inside of the body of a loop you can use all the tools you use elsewhere in Python.</p>
<p>Here is one more example of a loop, this time iterating over all the chapters and calculating the number of paragraphs in each chapter.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb569-1" data-line-number="1"><span class="cf">for</span> chapter <span class="kw">in</span> alice_chapters[<span class="dv">1</span>:]:</a>
<a class="sourceLine" id="cb569-2" data-line-number="2">    paragraphs <span class="op">=</span> chapter.split(<span class="st">&quot;</span><span class="ch">\n\n</span><span class="st">&quot;</span>)</a>
<a class="sourceLine" id="cb569-3" data-line-number="3">    <span class="bu">print</span>(<span class="bu">len</span>(paragraphs))</a></code></pre></div>
<pre><code>## 33
## 29
## 51
## 45
## 81
## 84
## 108
## 74
## 95
## 88
## 77
## 73</code></pre>
</div>
<div id="organizing-results-in-dictionaries" class="section level3">
<h3>Organizing results in dictionaries</h3>
<p>It’s often useful to store separate pieces of data that are related to one another in a <code>dict</code> (i.e., “dictionary”), which is designed to store key-value pairs. For example, we can calculate the number of times “Alice” is mentioned per chapter and associate each count with the chapter title it corresponds to.</p>
<p>The dictionary structure looks like:</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb571-1" data-line-number="1"><span class="co"># mydict = {key1:value1, key2:value2, key3:value3}</span></a></code></pre></div>
<p>A simple example:</p>
<div class="sourceCode" id="cb572"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb572-1" data-line-number="1">mydict <span class="op">=</span> {<span class="st">&quot;apple&quot;</span>:<span class="dv">5</span>, <span class="st">&quot;pear&quot;</span>:<span class="dv">6</span>, <span class="st">&quot;grape&quot;</span>:<span class="dv">10</span>}</a>
<a class="sourceLine" id="cb572-2" data-line-number="2"><span class="bu">print</span>(mydict)</a></code></pre></div>
<pre><code>## {&#39;apple&#39;: 5, &#39;pear&#39;: 6, &#39;grape&#39;: 10}</code></pre>
<div class="sourceCode" id="cb574"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb574-1" data-line-number="1"><span class="co"># compare the above dict to a list</span></a>
<a class="sourceLine" id="cb574-2" data-line-number="2">mylist <span class="op">=</span>[<span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">10</span>]</a>
<a class="sourceLine" id="cb574-3" data-line-number="3"><span class="bu">print</span>(mylist)</a></code></pre></div>
<pre><code>## [5, 6, 10]</code></pre>
<p>To associate chapter titles with “Alice” counts, we will first need to learn how to <strong>append</strong> elements to a list:</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb576-1" data-line-number="1">container <span class="op">=</span> [] <span class="co"># a list</span></a>
<a class="sourceLine" id="cb576-2" data-line-number="2"></a>
<a class="sourceLine" id="cb576-3" data-line-number="3"><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</a>
<a class="sourceLine" id="cb576-4" data-line-number="4">    container.append(i) <span class="co"># append elements to the list</span></a>
<a class="sourceLine" id="cb576-5" data-line-number="5"></a>
<a class="sourceLine" id="cb576-6" data-line-number="6"><span class="bu">print</span>(container)    </a></code></pre></div>
<pre><code>## [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]</code></pre>
<p>Now, with the Alice text, first we can iterate over each chapter and grab just the first line (that is, the chapter titles). These will become our <strong>keys</strong>.</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb578-1" data-line-number="1">chapter_titles <span class="op">=</span> []</a>
<a class="sourceLine" id="cb578-2" data-line-number="2"></a>
<a class="sourceLine" id="cb578-3" data-line-number="3"><span class="cf">for</span> chapter <span class="kw">in</span> alice_chapters[<span class="dv">1</span>:]:</a>
<a class="sourceLine" id="cb578-4" data-line-number="4">    chapter_titles.append(chapter.split(sep<span class="op">=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)[<span class="dv">0</span>])</a>
<a class="sourceLine" id="cb578-5" data-line-number="5"></a>
<a class="sourceLine" id="cb578-6" data-line-number="6"><span class="bu">print</span>(chapter_titles)</a></code></pre></div>
<pre><code>## [&#39;I. Down the Rabbit-Hole&#39;, &#39;II. The Pool of Tears&#39;, &#39;III. A Caucus-Race and a Long Tale&#39;, &#39;IV. The Rabbit Sends in a Little Bill&#39;, &#39;V. Advice from a Caterpillar&#39;, &#39;VI. Pig and Pepper&#39;, &#39;VII. A Mad Tea-Party&#39;, &quot;VIII. The Queen&#39;s Croquet-Ground&quot;, &quot;IX. The Mock Turtle&#39;s Story&quot;, &#39;X. The Lobster Quadrille&#39;, &#39;XI. Who Stole the Tarts?&#39;, &quot;XII. Alice&#39;s Evidence&quot;]</code></pre>
<p>Next, we can iterate over each chapter and count the number of times “Alice” was mentioned. These will become our <strong>values</strong>.</p>
<div class="sourceCode" id="cb580"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb580-1" data-line-number="1">chapter_Alice <span class="op">=</span> []</a>
<a class="sourceLine" id="cb580-2" data-line-number="2"></a>
<a class="sourceLine" id="cb580-3" data-line-number="3"><span class="cf">for</span> chapter <span class="kw">in</span> alice_chapters[<span class="dv">1</span>:]:</a>
<a class="sourceLine" id="cb580-4" data-line-number="4">    chapter_Alice.append(chapter.count(<span class="st">&quot;Alice&quot;</span>))</a></code></pre></div>
<p>Finally we can combine the chapter titles (<strong>keys</strong>) and “Alice” counts (<strong>values</strong>) and convert them to a dictionary.</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb581-1" data-line-number="1"><span class="co"># combine titles and counts</span></a>
<a class="sourceLine" id="cb581-2" data-line-number="2">mydict <span class="op">=</span> <span class="bu">dict</span>(<span class="bu">zip</span>(chapter_titles, chapter_Alice))</a>
<a class="sourceLine" id="cb581-3" data-line-number="3"></a>
<a class="sourceLine" id="cb581-4" data-line-number="4"><span class="bu">print</span>(mydict)</a></code></pre></div>
<pre><code>## {&#39;I. Down the Rabbit-Hole&#39;: 28, &#39;II. The Pool of Tears&#39;: 24, &#39;III. A Caucus-Race and a Long Tale&#39;: 23, &#39;IV. The Rabbit Sends in a Little Bill&#39;: 31, &#39;V. Advice from a Caterpillar&#39;: 35, &#39;VI. Pig and Pepper&#39;: 43, &#39;VII. A Mad Tea-Party&#39;: 51, &quot;VIII. The Queen&#39;s Croquet-Ground&quot;: 39, &quot;IX. The Mock Turtle&#39;s Story&quot;: 52, &#39;X. The Lobster Quadrille&#39;: 30, &#39;XI. Who Stole the Tarts?&#39;: 16, &quot;XII. Alice&#39;s Evidence&quot;: 23}</code></pre>
<div class="sourceCode" id="cb583"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb583-1" data-line-number="1"><span class="bu">help</span>(<span class="bu">zip</span>)         </a></code></pre></div>
<pre><code>## Help on class zip in module builtins:
## 
## class zip(object)
##  |  zip(*iterables) --&gt; zip object
##  |  
##  |  Return a zip object whose .__next__() method returns a tuple where
##  |  the i-th element comes from the i-th iterable argument.  The .__next__()
##  |  method continues until the shortest iterable in the argument sequence
##  |  is exhausted and then it raises StopIteration.
##  |  
##  |  Methods defined here:
##  |  
##  |  __getattribute__(self, name, /)
##  |      Return getattr(self, name).
##  |  
##  |  __iter__(self, /)
##  |      Implement iter(self).
##  |  
##  |  __next__(self, /)
##  |      Implement next(self).
##  |  
##  |  __reduce__(...)
##  |      Return state information for pickling.
##  |  
##  |  ----------------------------------------------------------------------
##  |  Static methods defined here:
##  |  
##  |  __new__(*args, **kwargs) from builtins.type
##  |      Create and return a new object.  See help(type) for accurate signature.</code></pre>
</div>
<div id="exercise-2-3" class="section level3">
<h3>Exercise 2</h3>
<p><strong>Iterating &amp; counting things</strong></p>
<p>Now that we know how to iterate using for-loops, the possibilities really start to open up. For example, we can use these techniques to count the number of times each character appears in the story.</p>
<ol style="list-style-type: decimal">
<li>Make sure you have both the text and the list of characters.</li>
</ol>
<p>Open and read both “Alice_in_wonderland.txt” and
“Characters.txt” if you have not already done so.</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb585-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Which chapter has the most words?</li>
</ol>
<p>Split the text into chapters (i.e., split on “CHAPTER”) and use a for-loop to iterate over the chapters.
For each chapter, split it into words and calculate the length.</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb586-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>How many times is each character mentioned in the text?</li>
</ol>
<p>Iterate over the list of characters using a for-loop.
For each character, call the count method with that character as the argument.</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb587-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>(BONUS, optional): Put the character counts computed
above in a dictionary with character names as the keys and
counts as the values.</li>
</ol>
<div class="sourceCode" id="cb588"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb588-1" data-line-number="1"><span class="co">##</span></a></code></pre></div>
<details>
<summary><span style="color:red"><b>Click for Exercise 2 Solution</b></span></summary>
<div class="alert alert-danger">
<ol style="list-style-type: decimal">
<li>Make sure you have both the text and the list of characters.
Open and read both “Alice_in_wonderland.txt” and “Characters.txt” if you have not already done so.</li>
</ol>
<div class="sourceCode" id="cb589"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb589-1" data-line-number="1">characters_txt <span class="op">=</span> <span class="bu">open</span>(<span class="st">&quot;Characters.txt&quot;</span>).read()</a>
<a class="sourceLine" id="cb589-2" data-line-number="2">alice_txt <span class="op">=</span> <span class="bu">open</span>(<span class="st">&quot;Alice_in_wonderland.txt&quot;</span>).read()</a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Which chapter has the most words?
Split the text into chapters (i.e., split on “CHAPTER”) and use a for-loop to iterate over the chapters.
For each chapter, split it into words and calculate the length.</li>
</ol>
<div class="sourceCode" id="cb590"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb590-1" data-line-number="1">words_per_chapter <span class="op">=</span> []</a>
<a class="sourceLine" id="cb590-2" data-line-number="2"><span class="cf">for</span> chapter <span class="kw">in</span> alice_chapters:</a>
<a class="sourceLine" id="cb590-3" data-line-number="3">    words_per_chapter.append(<span class="bu">len</span>(chapter.split()))</a>
<a class="sourceLine" id="cb590-4" data-line-number="4">words_per_chapter</a></code></pre></div>
<pre><code>## [7, 2184, 2098, 1701, 2614, 2185, 2592, 2286, 2486, 2271, 2028, 1877, 2104]</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>How many times is each character mentioned in the text?
Iterate over the list of characters using a for-loop.
For each character, call the count method with that character as the argument.</li>
</ol>
<div class="sourceCode" id="cb592"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb592-1" data-line-number="1">num_per_character <span class="op">=</span> []</a>
<a class="sourceLine" id="cb592-2" data-line-number="2"><span class="cf">for</span> character <span class="kw">in</span> characters_txt.split(sep<span class="op">=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>):</a>
<a class="sourceLine" id="cb592-3" data-line-number="3">    num_per_character.append(alice_txt.count(character))</a>
<a class="sourceLine" id="cb592-4" data-line-number="4">num_per_character</a></code></pre></div>
<pre><code>## [395, 20, 30, 13, 7, 3, 3, 3, 0, 0, 27, 42, 4, 30, 55, 40, 3, 3, 0, 55, 53, 144403]</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>(BONUS, optional): Put the character counts computed above in a
dictionary with character names as the keys and counts as the values.</li>
</ol>
<div class="sourceCode" id="cb594"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb594-1" data-line-number="1">characters <span class="op">=</span> characters_txt.split(sep<span class="op">=</span><span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)</a>
<a class="sourceLine" id="cb594-2" data-line-number="2"><span class="bu">dict</span>(<span class="bu">zip</span>(characters, num_per_character))</a></code></pre></div>
<pre><code>## {&#39;Alice&#39;: 395, &#39;White Rabbit&#39;: 20, &#39;Mouse&#39;: 30, &#39;Dodo&#39;: 13, &#39;Lory&#39;: 7, &#39;Eaglet&#39;: 3, &#39;Duck&#39;: 3, &#39;Pat&#39;: 3, &#39;Bill the Lizard&#39;: 0, &#39;Puppy&#39;: 0, &#39;Caterpillar&#39;: 27, &#39;Duchess&#39;: 42, &#39;Cheshire Cat&#39;: 4, &#39;March Hare&#39;: 30, &#39;Hatter&#39;: 55, &#39;Dormouse&#39;: 40, &#39;Queen of Hearts&#39;: 3, &#39;Knave of Hearts&#39;: 3, &#39;King of Hearts&#39;: 0, &#39;Gryphon&#39;: 55, &#39;Mock Turtle&#39;: 53, &#39;&#39;: 144403}</code></pre>
</div>
</details>
</div>
</div>
<div id="importing-packages" class="section level2">
<h2>Importing packages</h2>
<div class="alert alert-info">
<p><strong>GOAL: To learn how to expand Python’s functionality by importing packages.</strong></p>
<ol style="list-style-type: decimal">
<li>Import <code>numpy</code></li>
<li>Calculate simple statistics</li>
</ol>
</div>
<p>Now that we know how to iterate over lists and calculate numbers for each element, we may wish to do some simple math using these numbers. For example, we may want to calculate the mean and standard deviation of the distribution of the number of paragraphs in each chapter. Python has a handful of math functions built-in (e.g., <code>min()</code> and <code>max()</code>) but built-in math support is pretty limited.</p>
<p>When you find that something isn’t available in Python itself, its time to look for a package that does it. Although it is somewhat overkill for simply calculating a mean we’re going to use a popular package called <code>numpy</code> for this. The <code>numpy</code> package is included in the Anaconda Python distribution we are using, so we don’t need to install it separately.</p>
<p>To use <code>numpy</code> or other packages, you must first import them.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb596-1" data-line-number="1"><span class="co"># import &lt;package-name&gt;</span></a></code></pre></div>
<p>We can import <code>numpy</code> as follows:</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb597-1" data-line-number="1"><span class="im">import</span> numpy</a></code></pre></div>
<p>To use functions from a package, we can prefix the function with the package name, separated by a period:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb598-1" data-line-number="1"><span class="co"># &lt;package-name&gt;.&lt;function_name&gt;()</span></a></code></pre></div>
<p>The <code>numpy</code> package is very popular and includes a lot of useful functions. For example, we can use it to calculate means and standard deviations:</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb599-1" data-line-number="1"><span class="bu">print</span>(numpy.mean(chapter_Alice))</a></code></pre></div>
<pre><code>## 32.916666666666664</code></pre>
<div class="sourceCode" id="cb601"><pre class="sourceCode python"><code class="sourceCode python"><a class="sourceLine" id="cb601-1" data-line-number="1"><span class="bu">print</span>(numpy.std(chapter_Alice))</a></code></pre></div>
<pre><code>## 10.92747556493366</code></pre>
</div>
<div id="wrap-up-5" class="section level2">
<h2>Wrap-up</h2>
<div id="feedback-5" class="section level3">
<h3>Feedback</h3>
<p>These workshops are a work in progress, please provide any feedback to: <a href="mailto:help@iq.harvard.edu">help@iq.harvard.edu</a></p>
</div>
<div id="resources-7" class="section level3">
<h3>Resources</h3>
<ul>
<li>IQSS
<ul>
<li>Workshops: <a href="https://dss.iq.harvard.edu/workshop-materials" class="uri">https://dss.iq.harvard.edu/workshop-materials</a></li>
<li>Data Science Services: <a href="https://dss.iq.harvard.edu/" class="uri">https://dss.iq.harvard.edu/</a></li>
<li>Research Computing Environment: <a href="https://iqss.github.io/dss-rce/" class="uri">https://iqss.github.io/dss-rce/</a></li>
</ul></li>
<li>HBS
<ul>
<li>Research Computing Services workshops: <a href="https://training.rcs.hbs.org/workshops" class="uri">https://training.rcs.hbs.org/workshops</a></li>
<li>Other HBS RCS resources: <a href="https://training.rcs.hbs.org/workshop-materials" class="uri">https://training.rcs.hbs.org/workshop-materials</a></li>
<li>RCS consulting email: <a href="mailto:research@hbs.edu">mailto:research@hbs.edu</a></li>
</ul></li>
<li>Graphics
<ul>
<li>matplotlib: <a href="https://matplotlib.org/" class="uri">https://matplotlib.org/</a></li>
<li>seaborn: <a href="https://seaborn.pydata.org/" class="uri">https://seaborn.pydata.org/</a></li>
<li>plotly: <a href="https://plot.ly/python/" class="uri">https://plot.ly/python/</a></li>
</ul></li>
<li>Quantitative Data Analysis
<ul>
<li>numpy: <a href="http://www.numpy.org/" class="uri">http://www.numpy.org/</a></li>
<li>scipy: <a href="https://www.scipy.org/" class="uri">https://www.scipy.org/</a></li>
<li>pandas: <a href="https://pandas.pydata.org/" class="uri">https://pandas.pydata.org/</a></li>
<li>scikit-learn: <a href="http://scikit-learn.org/stable/" class="uri">http://scikit-learn.org/stable/</a></li>
<li>statsmodels: <a href="http://www.statsmodels.org/stable/" class="uri">http://www.statsmodels.org/stable/</a></li>
</ul></li>
<li>Text analysis
<ul>
<li>textblob: <a href="https://textblob.readthedocs.io/en/dev/" class="uri">https://textblob.readthedocs.io/en/dev/</a></li>
<li>nltk: <a href="http://www.nltk.org/" class="uri">http://www.nltk.org/</a></li>
<li>Gensim: <a href="https://radimrehurek.com/gensim/" class="uri">https://radimrehurek.com/gensim/</a></li>
</ul></li>
<li>Webscraping
<ul>
<li>scrapy: <a href="https://scrapy.org/" class="uri">https://scrapy.org/</a></li>
<li>requests: <a href="http://docs.python-requests.org/en/master/" class="uri">http://docs.python-requests.org/en/master/</a></li>
<li>lxml: <a href="https://lxml.de/" class="uri">https://lxml.de/</a></li>
<li>BeautifulSoup: <a href="https://www.crummy.com/software/BeautifulSoup/" class="uri">https://www.crummy.com/software/BeautifulSoup/</a></li>
</ul></li>
<li>Social Network Analysis
<ul>
<li>networkx: <a href="https://networkx.github.io/" class="uri">https://networkx.github.io/</a></li>
<li>graph-tool: <a href="https://graph-tool.skewed.de/" class="uri">https://graph-tool.skewed.de/</a></li>
</ul></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PythonInstall.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="PythonWebScrape.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/IQSS/dss-workshops/edit/master/Python/PythonIntro/PythonIntro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Data_Science_Workshops.pdf", "Data_Science_Workshops.epub"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
